In [40]:
import pandas as pd
import yfinance as yf

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

start_date = "2021-12-31"
end_date   = "2025-12-31"

**SOXX ETF Top 25 Holdings**

*Semiconductors*

In [41]:
soxx_hold = [
    "NVDA", "MU", "AMD", "AVGO", "AMAT", "LRCX", "NXPI", "ADI", "KLAC",
    "TXN", "QCOM", "ASML", "MPWR", "TSM", "INTC", "MCHP", "MRVL", "TER",
    "ON", "CRDO", "ALAB", "ENTG", "NVMI", "MTSI", "RMBS"
]

soxx_data = yf.download(soxx_hold, start=start_date, end=end_date, auto_adjust=False)      #yf.download works better than yf.history for multiple tickers
                                                                                          #Auto-adjust=false ensures stock splits and dividend payouts don't adjust close prices. (Negative Close prices appeared before)
soxx_data = soxx_data['Close']      #Keep only necessary 'Close' column as returns and therefore volatility will be worked out from this

soxx_data.index = pd.to_datetime(soxx_data.index)

soxx_data.ffill(inplace=True)       #Forward fill carries the previous days 'Close' price to the next day. Needed as ETFs often hold assets from multiple markets that have different trading weeks

[*********************100%***********************]  25 of 25 completed

In [42]:
soxx_data.columns
soxx_data.head(300)

Ticker,ADI,ALAB,AMAT,AMD,ASML,AVGO,CRDO,ENTG,INTC,KLAC,LRCX,MCHP,MPWR,MRVL,MTSI,MU,NVDA,NVMI,NXPI,ON,QCOM,RMBS,TER,TSM,TXN
Date,,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,175.770004,NaN,157.360001,143.899994,796.140015,66.541000,NaN,138.580002,51.500000,430.109985,71.915001,87.059998,493.329987,87.489998,78.300003,93.150002,29.410999,146.500000,227.779999,67.919998,182.869995,29.389999,163.529999,120.309998,188.470001
2022-01-03,177.149994,NaN,159.929993,150.240005,797.489990,66.332001,NaN,138.389999,53.209999,435.089996,72.545998,88.000000,494.850006,89.430000,79.750000,95.750000,30.121000,147.119995,231.220001,70.169998,186.210007,29.320000,166.110001,128.800003,190.600006
2022-01-04,175.550003,NaN,158.360001,144.419998,779.190002,67.092003,NaN,139.220001,53.139999,431.239990,71.199997,87.470001,491.250000,88.370003,78.580002,96.339996,29.290001,144.830002,232.869995,70.949997,187.229996,28.980000,166.380005,133.399994,190.800003
2022-01-05,172.839996,NaN,153.740005,136.149994,745.669983,64.300003,NaN,132.089996,53.869999,420.739990,69.181000,84.519997,460.529999,84.120003,73.739998,94.400002,27.604000,136.949997,224.570007,67.419998,186.500000,27.910000,160.250000,127.059998,186.820007
2022-01-06,173.389999,NaN,156.339996,136.229996,763.119995,63.702999,NaN,134.970001,54.009998,432.220001,70.191002,85.300003,465.609985,85.529999,74.680000,95.650002,28.177999,137.000000,226.960007,67.250000,185.949997,28.129999,163.479996,128.470001,186.759995
2022-01-07,168.839996,NaN,150.809998,132.000000,756.099976,61.915001,NaN,132.009995,53.439999,416.910004,66.929001,81.930000,444.690002,83.110001,72.480003,94.449997,27.247000,131.990005,221.330002,64.559998,180.410004,27.540001,158.270004,123.500000,179.440002
2022-01-10,170.399994,NaN,149.589996,132.000000,727.169983,62.116001,NaN,133.910004,55.209999,418.730011,66.429001,82.930000,449.329987,82.209999,72.839996,93.889999,27.400000,131.360001,221.830002,65.120003,179.679993,27.389999,156.610001,125.010002,182.960007
2022-01-11,173.630005,NaN,152.449997,137.309998,729.159973,62.205002,NaN,135.089996,55.910000,425.609985,67.320999,84.610001,452.510010,86.230003,73.610001,94.199997,27.816999,135.110001,227.539993,65.930000,185.399994,27.690001,160.539993,129.169998,184.639999
2022-01-12,173.750000,NaN,159.550003,137.470001,742.169983,62.200001,NaN,135.160004,55.740002,433.859985,68.632004,85.230003,448.910004,84.940002,74.190002,95.110001,27.999001,138.179993,229.020004,66.489998,186.419998,28.040001,162.899994,132.229996,186.029999
2022-01-13,169.779999,NaN,157.179993,132.740005,730.080017,59.719002,NaN,131.820007,54.939999,421.480011,68.677002,83.690002,433.609985,78.650002,71.650002,95.620003,26.575001,135.110001,221.860001,64.639999,183.889999,27.860001,158.250000,139.190002,184.149994
2022-01-14,172.000000,NaN,167.000000,136.880005,744.530029,59.637001,NaN,133.619995,55.700001,445.000000,72.982002,84.290001,438.179993,83.000000,71.620003,97.360001,26.941999,142.149994,225.289993,66.199997,188.690002,27.959999,164.570007,140.660004,187.009995
2022-01-18,166.500000,NaN,152.360001,131.929993,715.229980,57.778999,NaN,127.480003,54.759998,412.980011,67.901001,79.330002,416.350006,77.669998,69.150002,92.870003,25.903000,131.149994,217.419998,63.029999,178.860001,26.459999,155.559998,133.830002,182.279999
2022-01-19,163.059998,NaN,143.070007,128.270004,698.820007,56.396999,NaN,127.419998,53.619999,393.190002,64.273003,76.660004,413.970001,76.889999,67.050003,90.000000,25.066999,124.120003,210.949997,59.009998,172.470001,25.900000,148.320007,131.009995,178.300003
2022-01-20,158.630005,NaN,139.149994,121.889999,706.460022,54.771999,NaN,123.940002,52.040001,383.279999,61.966999,73.970001,404.160004,73.800003,65.730003,85.070000,24.150000,119.900002,199.610001,55.540001,166.500000,25.030001,145.479996,128.330002,173.449997
2022-01-21,159.520004,NaN,135.059998,118.809998,694.729980,53.323002,NaN,120.230003,52.040001,373.029999,60.578999,73.330002,397.429993,72.550003,65.059998,81.930000,23.374001,114.220001,199.949997,54.730000,164.929993,24.600000,143.389999,124.529999,175.639999
2022-01-24,161.440002,NaN,139.289993,116.529999,687.419983,54.158001,NaN,122.849998,51.939999,391.100006,62.181999,74.849998,402.019989,72.089996,66.760002,82.949997,23.372000,116.830002,203.070007,55.340000,170.070007,24.910000,147.440002,125.959999,178.339996
2022-01-25,155.770004,NaN,132.990005,111.129997,648.570007,53.414001,NaN,116.239998,51.000000,370.109985,58.823002,72.540001,374.869995,67.019997,62.500000,80.720001,22.323999,113.199997,194.770004,53.320000,165.449997,24.330000,138.289993,122.480003,173.960007
2022-01-26,159.770004,NaN,135.580002,110.709999,653.260010,55.712002,NaN,116.440002,51.689999,380.600006,59.667000,74.389999,378.209991,67.660004,63.070000,81.970001,22.771999,118.279999,196.960007,55.759998,167.000000,24.530001,143.369995,123.080002,178.330002
2022-01-27,154.589996,NaN,130.149994,102.599998,634.659973,54.230999,11.650000,109.730003,48.049999,361.799988,55.529999,71.040001,361.119995,64.889999,58.080002,78.720001,21.944000,109.300003,187.960007,53.669998,161.199997,23.760000,111.239998,116.379997,174.809998
2022-01-28,158.630005,NaN,132.449997,105.239998,644.969971,56.009998,11.190000,111.489998,47.730000,366.649994,56.113998,72.220001,370.890015,66.320000,60.080002,79.269997,22.840000,109.370003,189.449997,53.759998,166.809998,24.139999,112.120003,117.610001,177.289993
2022-01-31,163.970001,NaN,138.179993,114.250000,677.200012,58.588001,12.120000,119.839996,48.820000,389.269989,58.992001,77.480003,402.929993,71.400002,61.209999,82.269997,24.486000,118.300003,205.440002,59.000000,175.759995,25.250000,117.430000,122.629997,179.490005
2022-02-01,165.369995,NaN,138.610001,116.779999,681.479980,59.271999,12.800000,128.440002,48.950001,388.029999,58.946999,78.290001,406.339996,72.419998,61.279999,81.449997,24.638000,116.220001,208.199997,59.650002,177.130005,25.559999,116.879997,123.050003,181.289993
2022-02-02,168.910004,NaN,140.759995,122.760002,686.750000,60.342999,13.400000,132.550003,49.509998,395.459991,61.176998,79.040001,414.500000,74.080002,60.660000,84.510002,25.242001,118.419998,210.350006,61.080002,188.199997,25.730000,117.220001,124.150002,187.839996
2022-02-03,162.020004,NaN,136.509995,120.080002,645.929993,58.084999,12.820000,126.110001,48.279999,373.679993,58.875999,74.169998,393.160004,68.629997,58.080002,81.970001,23.948000,111.290001,198.339996,56.209999,179.100006,25.070000,111.860001,119.839996,175.589996
2022-02-04,161.029999,NaN,135.570007,123.599998,652.809998,59.015999,13.070000,128.559998,48.009998,377.380005,57.907001,73.180000,400.119995,71.099998,58.669998,81.169998,24.319000,115.959999,198.119995,57.419998,179.470001,24.830000,114.010002,121.019997,171.419998
2022-02-07,160.820007,NaN,136.130005,123.669998,650.030029,58.763000,13.520000,127.440002,48.180000,375.600006,57.137001,73.650002,396.950012,71.570000,58.060001,80.870003,24.728001,115.669998,196.919998,62.259998,175.089996,25.160000,114.230003,122.309998,169.949997
2022-02-08,163.130005,NaN,138.750000,128.229996,653.469971,60.021999,13.940000,130.000000,48.810001,385.220001,57.629002,75.440002,405.600006,76.500000,59.650002,84.120003,25.108000,118.550003,202.529999,65.970001,178.589996,26.350000,116.389999,123.709999,172.630005
2022-02-09,168.210007,NaN,144.199997,132.850006,680.369995,61.133999,14.640000,133.589996,49.910000,400.130005,60.743999,78.430000,422.809998,77.739998,61.270000,88.120003,26.705000,121.370003,209.759995,67.080002,183.949997,27.139999,121.370003,125.519997,176.710007
2022-02-10,161.669998,NaN,139.770004,125.769997,656.880005,59.136002,15.190000,131.630005,48.860001,389.709991,59.487000,74.930000,407.290009,73.839996,60.220001,91.019997,25.823999,118.430000,199.050003,63.419998,174.070007,27.040001,117.330002,124.709999,170.660004
2022-02-11,153.899994,NaN,132.490005,113.180000,628.239990,57.341999,15.300000,124.480003,47.630001,369.230011,55.999001,71.330002,424.290009,67.989998,58.200001,89.760002,23.948999,112.459999,186.740005,58.970001,164.639999,26.410000,113.089996,121.010002,164.399994
2022-02-14,153.979996,NaN,131.860001,114.269997,627.909973,57.858002,14.860000,126.040001,47.580002,365.160004,55.825001,71.190002,433.320007,67.750000,58.000000,89.860001,24.267000,111.919998,185.880005,58.660000,165.130005,26.309999,112.309998,119.769997,162.470001
2022-02-15,162.039993,NaN,139.839996,121.470001,656.409973,60.277000,14.990000,134.059998,48.439999,387.500000,59.382000,74.980003,479.269989,74.169998,61.270000,96.000000,26.495001,118.480003,196.619995,62.240002,173.000000,27.340000,118.099998,124.519997,166.169998
2022-02-16,168.339996,NaN,140.960007,117.690002,663.859985,59.721001,15.070000,135.389999,48.230000,385.649994,59.146999,75.500000,487.570007,72.099998,61.680000,96.059998,26.511000,118.610001,199.660004,63.110001,172.600006,28.070000,119.110001,123.599998,168.240005
2022-02-17,160.429993,NaN,136.470001,112.370003,650.429993,57.900002,15.120000,133.500000,47.570000,366.049988,58.061001,71.169998,461.880005,67.550003,59.180000,93.730003,24.507000,117.000000,187.610001,60.189999,166.800003,27.309999,116.000000,119.760002,164.649994
2022-02-18,160.360001,NaN,133.350006,113.830002,647.830017,57.999001,15.200000,130.190002,45.040001,358.299988,56.999001,71.779999,457.350006,67.339996,58.650002,90.800003,23.642000,114.940002,187.089996,60.200001,167.639999,26.740000,114.830002,119.309998,166.740005
2022-02-22,160.880005,NaN,130.259995,115.650002,640.270020,57.745998,15.620000,126.849998,44.689999,355.739990,55.972000,71.790001,450.109985,66.699997,58.230000,90.570000,23.389999,112.650002,187.240005,58.439999,165.889999,26.290001,113.809998,116.910004,166.690002
2022-02-23,156.490005,NaN,127.860001,109.760002,631.729980,56.519001,15.120000,124.370003,44.650002,343.779999,54.238998,70.300003,431.410004,64.820000,56.950001,87.309998,22.386999,108.629997,185.149994,57.750000,161.619995,25.930000,111.519997,115.900002,165.639999
2022-02-24,159.789993,NaN,133.419998,116.610001,656.840027,58.000000,14.930000,132.190002,46.720001,357.890015,56.287998,71.260002,455.140015,67.790001,59.880001,88.830002,23.747999,112.500000,191.419998,61.080002,167.979996,26.760000,117.389999,111.879997,169.589996
2022-02-25,162.119995,NaN,135.720001,121.059998,667.119995,58.800999,15.330000,133.339996,47.709999,357.649994,57.320000,72.150002,461.440002,68.750000,60.520000,90.099998,24.157000,108.839996,194.199997,63.500000,170.929993,27.200001,120.040001,111.230003,170.820007
2022-02-28,160.289993,NaN,134.199997,123.339996,666.510010,58.743999,16.900000,130.479996,47.700001,348.500000,56.134998,70.330002,458.700012,68.330002,60.099998,88.860001,24.385000,104.779999,190.119995,62.610001,171.990005,27.000000,117.919998,107.010002,169.990005
2022-03-01,156.949997,NaN,129.610001,113.830002,634.210022,57.012001,15.220000,123.040001,46.820000,336.790009,54.056999,67.900002,436.600006,64.949997,57.959999,86.260002,23.476999,105.449997,181.179993,59.650002,163.690002,26.680000,114.559998,108.050003,167.289993
2022-03-02,159.820007,NaN,133.179993,118.279999,655.369995,58.577999,16.360001,126.000000,48.869999,346.070007,55.402000,69.739998,453.450012,67.669998,60.259998,93.300003,24.219999,111.180000,188.350006,62.869999,169.250000,28.010000,117.300003,109.610001,170.100006
2022-03-03,159.279999,NaN,130.639999,111.980003,630.789978,57.860001,16.100000,122.779999,47.930000,342.529999,54.351002,69.040001,430.000000,65.199997,58.730000,89.180000,23.714001,106.879997,184.699997,61.509998,165.350006,28.830000,114.169998,108.790001,171.000000
2022-03-04,156.850006,NaN,125.739998,108.410004,594.320007,59.598999,15.660000,116.309998,48.070000,332.100006,52.577999,67.760002,413.779999,63.410000,57.790001,81.910004,22.936001,100.300003,176.449997,58.330002,162.259995,28.090000,111.750000,105.059998,169.979996
2022-03-07,146.279999,NaN,119.220001,102.949997,574.340027,57.070000,15.860000,114.989998,47.680000,314.140015,48.915001,65.139999,381.500000,61.169998,55.630001,75.699997,21.351999,99.660004,169.720001,53.520000,150.100006,27.190001,106.419998,99.290001,164.889999
2022-03-08,148.520004,NaN,124.150002,105.529999,573.039978,57.595001,15.730000,119.690002,47.500000,321.820007,49.036999,68.529999,394.440002,64.510002,57.150002,77.160004,21.514000,105.839996,176.899994,55.790001,150.759995,27.870001,107.550003,100.000000,167.339996
2022-03-09,153.619995,NaN,128.619995,111.050003,621.340027,59.702000,16.440001,125.330002,47.630001,339.559998,51.730999,70.879997,418.160004,66.550003,59.570000,79.440002,23.014000,110.930000,183.350006,58.430000,157.110001,28.740000,111.750000,104.949997,172.460007
2022-03-10,150.559998,NaN,124.970001,106.459999,600.070007,58.772999,16.160000,123.730003,46.660000,328.790009,49.707001,69.849998,409.059998,65.250000,58.570000,75.720001,22.658001,107.510002,180.500000,57.630001,154.710007,28.280001,109.959999,103.959999,172.750000
2022-03-11,147.600006,NaN,123.639999,104.290001,585.849976,57.785000,15.510000,120.769997,45.830002,323.269989,48.339001,69.040001,395.739990,63.090000,56.439999,72.820000,22.100000,105.629997,178.559998,55.889999,152.339996,27.730000,106.879997,101.410004,170.360001
2022-03-14,145.630005,NaN,120.129997,102.250000,577.549988,56.779999,13.670000,119.750000,44.400002,320.000000,46.900002,68.129997,385.010010,60.250000,53.970001,69.400002,21.330000,99.699997,171.710007,53.910000,141.289993,25.780001,105.570000,99.300003,166.720001
2022-03-15,150.919998,NaN,124.410004,109.330002,596.700012,59.276001,14.300000,124.169998,44.810001,333.220001,48.472000,71.620003,421.820007,65.779999,56.220001,73.110001,22.973000,104.989998,178.440002,56.660000,144.210007,27.870001,110.510002,102.089996,172.320007
2022-03-16,158.570007,NaN,130.479996,115.370003,650.630005,60.712002,14.630000,133.850006,46.630001,350.920013,51.449001,74.750000,440.679993,68.910004,58.529999,79.669998,24.496000,111.040001,188.320007,60.110001,150.449997,29.010000,116.750000,105.690002,176.330002
2022-03-17,159.979996,NaN,131.990005,111.690002,654.099976,60.266998,14.120000,134.850006,47.139999,352.609985,52.632000,75.419998,451.239990,69.410004,59.200001,80.519997,24.766001,111.910004,189.770004,60.759998,152.830002,29.629999,120.599998,106.489998,178.470001
2022-03-18,163.449997,NaN,135.139999,113.459999,679.859985,61.041000,13.690000,134.839996,47.450001,365.049988,54.464001,77.290001,469.880005,71.330002,61.150002,79.410004,26.452999,114.989998,192.419998,61.930000,153.990005,31.230000,122.949997,106.720001,180.100006
2022-03-21,164.220001,NaN,134.199997,115.919998,682.909973,60.129002,12.760000,135.000000,47.389999,356.279999,53.686001,76.570000,464.429993,70.709999,61.779999,78.349998,26.733999,113.650002,190.509995,61.930000,155.589996,31.209999,120.940002,106.919998,180.460007
2022-03-22,164.770004,NaN,135.479996,114.779999,688.739990,61.133999,13.310000,134.759995,48.389999,361.029999,54.675999,76.389999,470.149994,71.379997,61.990002,79.120003,26.524000,115.089996,187.750000,62.180000,157.610001,31.389999,121.000000,107.040001,182.350006
2022-03-23,159.139999,NaN,131.419998,113.919998,665.359985,59.938000,13.420000,132.309998,48.270000,348.730011,53.098999,73.769997,463.720001,68.940002,59.869999,75.650002,25.634001,111.870003,183.589996,60.389999,152.869995,31.170000,116.510002,105.349998,179.080002
2022-03-24,164.960007,NaN,138.589996,120.529999,690.539978,62.643002,14.490000,136.270004,51.619999,365.890015,55.622002,77.680000,494.619995,73.760002,61.580002,78.209999,28.150000,114.650002,191.080002,63.580002,158.460007,32.430000,122.690002,107.919998,184.210007
2022-03-25,165.630005,NaN,137.059998,119.669998,687.359985,62.887001,14.470000,136.889999,51.830002,366.440002,55.481998,77.160004,491.519989,74.370003,62.250000,78.099998,27.691999,111.180000,190.460007,63.810001,157.970001,32.310001,124.040001,106.730003,184.899994
2022-03-28,167.259995,NaN,137.660004,120.239998,694.830017,63.287998,14.300000,137.520004,51.509998,375.350006,55.730999,77.449997,499.420013,74.309998,61.389999,79.860001,28.219000,112.629997,189.419998,65.320000,158.449997,32.919998,122.959999,106.330002,185.679993
2022-03-29,170.179993,NaN,141.440002,123.230003,709.140015,64.147003,15.330000,140.830002,52.250000,384.329987,56.893002,79.779999,512.210022,76.160004,62.580002,82.050003,28.656000,116.650002,194.740005,67.360001,161.070007,33.599998,125.370003,109.250000,191.009995
2022-03-30,166.479996,NaN,135.800003,119.220001,684.559998,63.109001,15.300000,135.440002,51.430000,373.820007,54.855999,76.389999,488.399994,73.010002,60.779999,79.160004,27.690001,110.870003,187.330002,64.430000,152.729996,32.299999,121.029999,106.730003,187.449997
2022-03-31,165.179993,NaN,131.800003,109.339996,667.929993,62.967999,15.230000,131.259995,49.560001,366.059998,53.761002,75.139999,485.679993,71.709999,59.869999,77.889999,27.285999,108.879997,185.080002,62.610001,152.820007,31.889999,118.230003,104.260002,183.479996
2022-04-01,165.360001,NaN,127.410004,108.190002,667.729980,62.698002,14.420000,125.129997,48.110001,360.269989,52.544998,73.970001,463.600006,71.070000,58.410000,76.180000,26.712000,107.150002,182.020004,59.630001,146.990005,31.430000,116.370003,102.790001,182.080002
2022-04-04,164.500000,NaN,129.440002,110.529999,680.830017,63.485001,14.620000,124.500000,49.200001,367.049988,53.555000,74.379997,474.529999,72.959999,59.599998,77.669998,27.360001,109.739998,182.610001,59.590000,153.809998,31.090000,118.940002,104.790001,182.710007
2022-04-05,159.979996,NaN,121.709999,106.820000,646.460022,61.411999,14.100000,117.349998,48.130001,345.519989,50.363998,70.089996,439.380005,68.309998,56.000000,74.610001,25.931000,103.750000,175.070007,55.700001,145.460007,28.620001,111.910004,102.500000,177.179993
2022-04-06,160.279999,NaN,119.330002,103.669998,628.510010,60.200001,14.050000,112.980003,47.540001,344.250000,49.817001,68.279999,431.250000,66.500000,53.450001,73.779999,24.407000,101.760002,174.020004,53.700001,139.279999,27.480000,111.199997,101.180000,177.250000
2022-04-07,161.250000,NaN,122.400002,103.720001,625.299988,60.305000,13.560000,114.739998,47.560001,353.079987,50.334000,68.190002,436.309998,65.660004,53.240002,73.279999,24.208000,103.250000,172.919998,54.090000,139.220001,27.160000,111.419998,100.519997,177.600006
2022-04-08,158.740005,NaN,119.959999,101.000000,610.929993,58.700001,13.440000,109.320000,47.020000,341.209991,49.164001,66.320000,411.589996,63.150002,51.349998,72.139999,23.118999,101.489998,167.500000,52.730000,136.690002,26.250000,108.660004,99.290001,174.110001
2022-04-11,154.889999,NaN,116.239998,97.370003,597.739990,58.061001,12.930000,107.900002,46.570000,331.470001,47.576000,65.809998,396.109985,60.730000,50.880001,72.029999,21.917000,99.050003,165.520004,52.330002,135.360001,25.540001,107.239998,97.570000,171.940002
2022-04-12,155.500000,NaN,114.559998,95.099998,594.000000,58.507000,12.770000,110.309998,46.500000,330.250000,46.700001,65.470001,401.040009,60.130001,51.299999,71.959999,21.504000,98.510002,166.229996,53.139999,136.089996,25.370001,108.180000,97.440002,173.000000
2022-04-13,158.119995,NaN,116.860001,97.739998,612.760010,59.254002,12.090000,113.699997,47.009998,336.519989,47.261002,66.760002,420.640015,63.299999,52.209999,72.379997,22.202999,99.870003,171.029999,54.250000,140.500000,26.200001,109.610001,101.500000,175.110001
2022-04-14,156.500000,NaN,113.360001,93.059998,597.869995,57.384998,11.410000,110.110001,45.669998,321.480011,45.616001,65.220001,409.380005,60.970001,50.900002,70.129997,21.257999,97.180000,170.000000,53.259998,136.910004,25.889999,106.019997,98.360001,173.660004
2022-04-18,160.339996,NaN,114.870003,93.889999,605.580017,58.650002,11.380000,112.660004,46.639999,327.869995,47.055000,67.239998,425.920013,61.730000,51.820000,71.150002,21.783001,97.669998,173.250000,54.570000,139.320007,26.219999,108.139999,98.769997,176.559998

---
**PICK ETF Top 25 Holdings**

*Metals and Mining*

In [43]:
pick_hold = [
    "BHP", "FCX", "GLNCY", "VALE", "AAL", "NUE", "RIO",
    "GMEXICOB.MX", "FVJA.BE", "STLD", "1211.SR", "TECK", "VALT.L",
    "MT", "NPS.MU", "IZ1.BE", "ANTO.L", "BWJ0.F", "RS", "AA", "GXD.F",
    "PKX.BE", "HWHG.BE", "IPHB.F"
]

pick_data = yf.download(pick_hold, start=start_date, end=end_date, auto_adjust=False)

pick_data = pick_data['Close']

pick_data.index = pd.to_datetime(pick_data.index)

pick_data.ffill(inplace=True)

[*********************100%***********************]  24 of 24 completed
ERROR:yfinance:
4 Failed downloads:
ERROR:yfinance:['IZ1.BE', 'FVJA.BE', 'HWHG.BE', 'PKX.BE']: YFTzMissingError('possibly delisted; no timezone found')

In [44]:
pick_data.columns
pick_data.head(200)

Ticker,1211.SR,AA,AAL,ANTO.L,BHP,BWJ0.F,FCX,FVJA.BE,GLNCY,GMEXICOB.MX,GXD.F,HWHG.BE,IPHB.F,IZ1.BE,MT,NPS.MU,NUE,PKX.BE,RIO,RS,STLD,TECK,VALE,VALT.L
Date,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,NaN,59.580002,17.959999,1338.500000,53.835861,NaN,41.730000,NaN,10.08,89.290001,NaN,NaN,NaN,NaN,31.830000,NaN,114.150002,NaN,66.940002,162.220001,62.070000,28.820000,14.020000,2306.548096
2022-01-02,26.266666,59.580002,17.959999,1338.500000,53.835861,NaN,41.730000,NaN,10.08,89.290001,NaN,NaN,NaN,NaN,31.830000,NaN,114.150002,NaN,66.940002,162.220001,62.070000,28.820000,14.020000,2306.548096
2022-01-03,26.133333,60.360001,18.750000,1338.500000,53.826939,68.190002,41.480000,NaN,10.16,89.089996,7.125,NaN,12.535000,NaN,32.119999,2.8370,113.040001,NaN,66.730003,161.279999,61.660000,29.110001,13.810000,2306.548096
2022-01-04,26.333332,57.529999,19.020000,1369.000000,54.701160,71.230003,42.150002,NaN,10.45,88.230003,7.005,NaN,12.750000,NaN,32.970001,2.8830,117.070000,NaN,67.519997,163.570007,63.520000,29.200001,13.550000,2306.548096
2022-01-05,26.366667,58.549999,18.680000,1372.000000,55.352364,69.930000,41.680000,NaN,10.46,89.540001,7.160,NaN,12.865000,NaN,33.029999,2.9450,122.720001,NaN,68.709999,166.750000,65.959999,29.420000,13.660000,2306.548096
2022-01-06,26.700001,58.450001,18.570000,1328.000000,55.414806,70.269997,40.529999,NaN,10.48,90.510002,6.870,NaN,12.695000,NaN,33.490002,2.9620,116.599998,NaN,70.040001,165.490005,64.050003,29.100000,14.010000,2306.548096
2022-01-07,26.700001,62.369999,19.280001,1353.000000,57.413025,71.489998,41.880001,NaN,10.75,90.360001,6.875,NaN,12.310000,NaN,34.810001,3.0490,114.440002,NaN,72.239998,166.529999,62.310001,30.410000,14.810000,2306.548096
2022-01-09,27.333332,62.369999,19.280001,1353.000000,57.413025,71.489998,41.880001,NaN,10.75,90.360001,6.875,NaN,12.310000,NaN,34.810001,3.0490,114.440002,NaN,72.239998,166.529999,62.310001,30.410000,14.810000,2306.548096
2022-01-10,28.299999,61.540001,18.790001,1345.500000,56.333630,70.419998,41.619999,NaN,10.59,89.250000,6.940,NaN,12.345000,NaN,34.299999,3.0440,111.860001,NaN,72.709999,162.399994,60.590000,31.200001,14.650000,2306.548096
2022-01-11,28.633333,62.200001,19.020000,1342.000000,57.528992,69.349998,42.990002,NaN,10.63,89.970001,6.900,NaN,13.205000,NaN,35.389999,3.0980,110.839996,NaN,74.419998,164.179993,60.970001,32.439999,15.240000,2306.548096
2022-01-12,29.400000,61.880001,18.500000,1442.500000,59.901875,72.150002,45.150002,NaN,11.01,93.980003,7.665,NaN,13.285000,NaN,37.240002,3.1080,114.720001,NaN,76.070000,167.720001,63.599998,34.180000,15.550000,2306.548096
2022-01-13,29.833332,60.509998,19.340000,1435.000000,59.857269,71.370003,44.330002,NaN,11.01,93.989998,7.680,NaN,13.280000,NaN,37.279999,3.2670,112.720001,NaN,75.660004,165.589996,62.820000,33.639999,15.300000,2306.548096
2022-01-14,29.833332,61.389999,18.490000,1379.000000,59.741302,72.320000,44.080002,NaN,11.06,93.089996,7.460,NaN,13.390000,NaN,37.220001,3.3150,110.820000,NaN,75.400002,166.330002,62.209999,33.980000,15.380000,2306.548096
2022-01-16,30.833332,61.389999,18.490000,1379.000000,59.741302,72.320000,44.080002,NaN,11.06,93.089996,7.460,NaN,13.390000,NaN,37.220001,3.3150,110.820000,NaN,75.400002,166.330002,62.209999,33.980000,15.380000,2306.548096
2022-01-17,30.333332,61.389999,18.490000,1436.500000,59.741302,71.529999,44.080002,NaN,11.06,93.870003,7.445,NaN,12.705000,NaN,37.220001,3.2890,110.820000,NaN,75.400002,166.330002,62.209999,33.980000,15.380000,2306.548096
2022-01-18,29.533333,60.049999,17.900000,1439.000000,59.277431,72.599998,44.290001,NaN,11.21,93.519997,7.650,NaN,12.350000,NaN,35.270000,3.0800,106.699997,NaN,75.730003,163.899994,59.900002,34.160000,15.510000,2306.548096
2022-01-19,30.733334,59.630001,17.309999,1482.500000,61.088314,75.839996,44.080002,NaN,11.36,95.339996,7.675,NaN,13.325000,NaN,35.619999,2.9420,104.250000,NaN,77.919998,163.699997,58.959999,34.560001,16.180000,2306.548096
2022-01-20,31.233334,61.250000,16.760000,1464.000000,60.686886,75.690002,43.189999,NaN,11.09,93.660004,7.720,NaN,13.500000,NaN,34.139999,2.9590,100.339996,NaN,76.160004,160.729996,56.959999,33.320000,15.990000,2306.548096
2022-01-21,31.233334,56.209999,16.299999,1450.000000,57.957180,73.660004,40.990002,NaN,10.89,90.250000,7.475,NaN,13.220000,NaN,31.830000,2.9380,93.050003,NaN,74.360001,150.839996,52.450001,32.549999,15.600000,2306.548096
2022-01-23,30.366667,56.209999,16.299999,1450.000000,57.957180,73.660004,40.990002,NaN,10.89,90.250000,7.475,NaN,13.220000,NaN,31.830000,2.9380,93.050003,NaN,74.360001,150.839996,52.450001,32.549999,15.600000,2306.548096
2022-01-24,30.299999,58.020000,16.410000,1356.500000,57.636040,68.779999,39.959999,NaN,10.56,86.830002,7.215,NaN,12.455000,NaN,30.990000,2.9290,95.309998,NaN,73.269997,152.210007,54.700001,32.070000,15.310000,2306.548096
2022-01-25,30.333332,61.209999,16.459999,1379.000000,56.984837,70.879997,39.630001,NaN,10.55,87.889999,7.240,NaN,13.065000,NaN,30.549999,2.8170,94.190002,NaN,73.680000,151.520004,54.119999,32.349998,15.480000,2306.548096
2022-01-26,30.333332,60.750000,16.240000,1411.500000,57.511150,72.970001,38.430000,NaN,10.61,87.879997,7.290,NaN,13.495000,NaN,30.139999,2.8690,93.040001,NaN,74.029999,149.059998,53.119999,32.639999,15.530000,2306.548096
2022-01-27,30.333332,58.029999,15.780000,1391.500000,58.697590,74.139999,37.099998,NaN,10.71,85.529999,7.100,NaN,13.210000,NaN,28.680000,2.8250,96.739998,NaN,75.089996,150.600006,54.340000,31.889999,15.570000,2306.548096
2022-01-28,30.333332,57.400002,15.640000,1337.500000,57.243534,71.320000,36.040001,NaN,10.53,86.550003,7.310,NaN,12.940000,NaN,29.160000,2.7700,99.790001,NaN,73.129997,151.589996,54.919998,30.709999,15.580000,2306.548096
2022-01-30,30.666666,57.400002,15.640000,1337.500000,57.243534,71.320000,36.040001,NaN,10.53,86.550003,7.310,NaN,12.940000,NaN,29.160000,2.7700,99.790001,NaN,73.129997,151.589996,54.919998,30.709999,15.580000,2306.548096
2022-01-31,30.633333,56.709999,16.469999,1332.500000,56.735058,70.370003,37.220001,NaN,10.37,88.589996,7.320,NaN,13.940000,NaN,29.660000,2.8420,101.400002,NaN,71.400002,152.880005,55.520000,30.870001,15.180000,2306.548096
2022-02-01,30.700001,58.169998,16.830000,1361.500000,58.001785,72.830002,39.020000,NaN,10.77,89.830002,7.480,NaN,13.025000,NaN,31.490000,2.8020,107.459999,NaN,74.199997,158.460007,57.610001,32.490002,16.180000,2306.548096
2022-02-02,30.866667,59.209999,16.959999,1284.000000,58.447815,73.489998,39.389999,NaN,10.86,90.139999,7.645,NaN,13.295000,NaN,31.790001,2.9070,111.980003,NaN,74.290001,160.050003,59.169998,32.380001,16.350000,2306.548096
2022-02-03,30.666666,62.740002,16.570000,1258.500000,58.644070,73.199997,38.200001,NaN,10.80,87.279999,7.295,NaN,13.000000,NaN,31.480000,2.8630,112.250000,NaN,73.470001,159.750000,58.869999,32.660000,16.150000,2306.548096
2022-02-04,30.666666,64.220001,16.450001,1227.000000,59.018734,72.669998,38.419998,NaN,10.92,88.870003,7.260,NaN,12.750000,NaN,31.469999,2.9070,111.260002,NaN,73.889999,156.139999,58.939999,33.230000,16.549999,2306.548096
2022-02-06,31.033333,64.220001,16.450001,1227.000000,59.018734,72.669998,38.419998,NaN,10.92,88.870003,7.260,NaN,12.750000,NaN,31.469999,2.9070,111.260002,NaN,73.889999,156.139999,58.939999,33.230000,16.549999,2306.548096
2022-02-07,31.233334,63.750000,17.280001,1233.500000,61.061550,74.330002,38.900002,NaN,11.06,88.870003,7.440,NaN,13.335000,NaN,32.389999,2.9480,111.120003,NaN,76.639999,154.039993,58.330002,34.160000,17.170000,2306.548096
2022-02-08,30.966665,69.970001,18.260000,1242.000000,61.694916,74.080002,40.630001,NaN,11.29,91.190002,7.700,NaN,13.090000,NaN,33.619999,3.0100,115.570000,NaN,78.099998,159.009995,60.599998,34.939999,17.430000,2306.548096
2022-02-09,31.333332,71.910004,18.760000,1290.000000,61.462978,75.150002,43.560001,NaN,11.37,93.510002,8.140,NaN,13.500000,NaN,34.299999,3.0810,120.080002,NaN,78.330002,163.149994,62.549999,35.950001,17.510000,2306.548096
2022-02-10,31.333332,71.169998,18.709999,1344.500000,62.390724,74.620003,43.910000,NaN,11.28,97.989998,8.460,NaN,13.795000,NaN,33.200001,3.1030,121.589996,NaN,78.959999,160.869995,61.340000,36.099998,17.850000,2306.548096
2022-02-11,31.333332,73.519997,17.610001,1366.500000,61.471901,75.199997,42.799999,NaN,11.16,101.290001,8.335,NaN,13.530000,NaN,30.690001,3.1000,118.410004,NaN,77.790001,160.869995,60.709999,36.430000,17.540001,2306.548096
2022-02-13,30.833332,73.519997,17.610001,1366.500000,61.471901,75.199997,42.799999,NaN,11.16,101.290001,8.335,NaN,13.530000,NaN,30.690001,3.1000,118.410004,NaN,77.790001,160.869995,60.709999,36.430000,17.540001,2306.548096
2022-02-14,31.166666,73.860001,17.430000,1389.500000,60.892059,76.110001,42.450001,NaN,11.44,102.180000,7.810,NaN,14.000000,NaN,29.730000,3.0860,117.349998,NaN,78.370003,161.850006,61.610001,35.799999,17.490000,2306.548096
2022-02-15,31.133333,74.040001,18.840000,1385.500000,60.231937,73.040001,43.669998,NaN,11.55,104.610001,8.305,NaN,13.505000,NaN,30.809999,2.9980,121.580002,NaN,77.129997,166.699997,63.779999,36.000000,17.139999,2306.548096
2022-02-16,31.900000,77.839996,18.820000,1403.000000,61.311329,74.120003,44.250000,NaN,11.56,105.849998,8.375,NaN,14.015000,NaN,31.760000,3.0680,122.660004,NaN,78.559998,168.199997,64.290001,36.220001,17.440001,2306.548096
2022-02-17,33.000000,76.470001,18.219999,1373.000000,60.588760,73.940002,43.209999,NaN,11.37,99.970001,8.255,NaN,14.680000,NaN,30.459999,3.0520,120.940002,NaN,76.680000,173.740005,63.240002,35.980000,16.600000,2306.548096
2022-02-18,33.000000,78.199997,17.870001,1404.000000,61.855488,75.419998,43.020000,NaN,11.41,98.449997,8.335,NaN,14.655000,NaN,30.330000,3.0890,122.930000,NaN,77.629997,174.949997,63.950001,35.490002,16.639999,2306.548096
2022-02-20,31.966665,78.199997,17.870001,1404.000000,61.855488,75.419998,43.020000,NaN,11.41,98.449997,8.335,NaN,14.655000,NaN,30.330000,3.0890,122.930000,NaN,77.629997,174.949997,63.950001,35.490002,16.639999,2306.548096
2022-02-21,32.700001,78.199997,17.870001,1396.000000,61.855488,73.360001,43.020000,NaN,11.41,96.720001,7.815,NaN,14.200000,NaN,30.330000,3.1440,122.930000,NaN,77.629997,174.949997,63.950001,35.490002,16.639999,2306.548096
2022-02-22,32.700001,74.089996,17.430000,1405.500000,61.320251,73.820000,42.360001,NaN,11.42,98.750000,7.760,NaN,14.990000,NaN,30.200001,3.0860,118.709999,NaN,77.769997,174.649994,63.040001,35.529999,17.180000,2306.548096
2022-02-23,32.599998,75.320000,16.639999,1439.500000,61.338093,73.980003,42.459999,NaN,11.55,97.809998,7.940,NaN,14.995000,NaN,29.719999,3.0700,117.980003,NaN,77.500000,172.669998,62.160000,35.450001,17.270000,2306.548096
2022-02-24,33.233334,73.300003,16.959999,1370.500000,56.645851,72.790001,43.720001,NaN,11.45,101.809998,7.520,NaN,15.975000,NaN,28.350000,3.0980,120.900002,NaN,75.419998,172.979996,63.259998,34.840000,17.070000,2306.548096
2022-02-25,33.233334,77.849998,17.459999,1447.500000,59.821587,77.500000,46.340000,NaN,11.91,101.919998,7.890,NaN,15.950000,NaN,31.650000,3.1190,130.050003,NaN,77.959999,183.419998,69.010002,36.840000,17.820000,2306.548096
2022-02-27,34.799999,77.849998,17.459999,1447.500000,59.821587,77.500000,46.340000,NaN,11.91,101.919998,7.890,NaN,15.950000,NaN,31.650000,3.1190,130.050003,NaN,77.959999,183.419998,69.010002,36.840000,17.820000,2306.548096
2022-02-28,35.599998,75.339996,17.250000,1521.000000,60.472794,77.730003,46.950001,NaN,11.72,105.070000,8.095,NaN,16.170000,NaN,30.940001,3.2320,131.619995,NaN,78.580002,190.869995,70.580002,35.950001,18.490000,2306.548096
2022-03-01,35.933334,79.779999,16.290001,1571.500000,61.106155,77.760002,47.910000,NaN,11.82,108.349998,8.595,NaN,16.834999,NaN,31.500000,3.2780,131.000000,NaN,80.029999,187.179993,72.169998,36.900002,18.860001,2306.548096
2022-03-02,37.133331,82.559998,16.370001,1576.500000,64.201607,88.500000,48.160000,NaN,12.15,109.419998,8.920,NaN,17.299999,NaN,32.889999,3.3200,138.009995,NaN,83.540001,189.210007,75.230003,38.709999,19.469999,2306.548096
2022-03-03,39.599998,82.889999,15.710000,1541.000000,65.120430,87.019997,49.090000,NaN,12.80,115.699997,8.880,NaN,16.455000,NaN,32.209999,3.3780,137.529999,NaN,84.000000,190.029999,77.089996,40.139999,19.840000,2306.548096
2022-03-04,39.599998,90.660004,14.590000,1532.000000,65.227478,83.300003,50.110001,NaN,12.28,116.980003,9.275,NaN,16.875000,NaN,29.340000,3.3780,138.720001,NaN,81.879997,188.860001,77.379997,41.490002,20.150000,2306.548096
2022-03-06,40.733334,90.660004,14.590000,1532.000000,65.227478,83.300003,50.110001,NaN,12.28,116.980003,9.275,NaN,16.875000,NaN,29.340000,3.3780,138.720001,NaN,81.879997,188.860001,77.379997,41.490002,20.150000,2306.548096
2022-03-07,43.333332,85.400002,12.840000,1545.500000,64.585190,81.980003,47.150002,NaN,12.47,117.199997,9.140,NaN,16.280001,NaN,27.959999,3.3780,131.899994,NaN,79.540001,184.690002,72.379997,39.200001,20.600000,2306.548096
2022-03-08,42.666664,82.370003,13.510000,1518.000000,62.060661,82.519997,46.669998,NaN,12.41,117.290001,9.110,NaN,15.805000,NaN,28.660000,3.2150,125.959999,NaN,77.529999,182.009995,69.970001,38.779999,19.820000,2306.548096
2022-03-09,41.333332,79.519997,14.300000,1498.000000,62.301517,78.449997,46.990002,NaN,12.34,114.419998,9.140,NaN,14.950000,NaN,30.010000,3.1090,130.009995,NaN,77.720001,189.009995,71.949997,40.090000,18.719999,2306.548096
2022-03-10,40.599998,82.940002,14.200000,1568.000000,63.523640,77.620003,47.709999,NaN,13.24,115.570000,9.000,NaN,15.510000,NaN,30.020000,3.1920,133.559998,NaN,74.849998,188.270004,72.389999,42.279999,19.309999,2306.548096
2022-03-11,40.599998,79.040001,14.020000,1576.000000,61.150757,80.339996,46.930000,NaN,13.19,113.680000,9.130,NaN,14.750000,NaN,29.820000,3.2390,135.250000,NaN,72.720001,188.229996,72.120003,41.860001,19.070000,2306.548096
2022-03-13,40.866665,79.040001,14.020000,1576.000000,61.150757,80.339996,46.930000,NaN,13.19,113.680000,9.130,NaN,14.750000,NaN,29.820000,3.2390,135.250000,NaN,72.720001,188.229996,72.120003,41.860001,19.070000,2306.548096
2022-03-14,39.733334,73.500000,14.250000,1556.000000,58.421055,79.400002,44.520000,NaN,12.34,108.410004,8.845,NaN,14.160000,NaN,30.010000,3.2920,132.050003,NaN,69.370003,187.669998,71.489998,38.349998,17.799999,2306.548096
2022-03-15,37.000000,73.709999,15.570000,1531.000000,57.787689,80.000000,44.279999,NaN,11.96,104.589996,8.235,NaN,14.310000,NaN,30.129999,3.1700,135.520004,NaN,69.080002,190.039993,73.110001,37.709999,17.240000,2306.548096
2022-03-16,40.666664,75.629997,16.469999,1632.500000,59.625336,83.330002,46.419998,NaN,12.61,103.339996,8.355,NaN,13.700000,NaN,32.040001,3.2820,135.110001,NaN,72.720001,189.470001,75.010002,37.529999,17.750000,2306.548096
2022-03-17,41.200001,80.730003,16.549999,1666.000000,60.570919,82.889999,48.590000,NaN,12.49,109.459999,8.740,NaN,14.445000,NaN,31.990000,3.2280,134.929993,NaN,74.839996,191.029999,81.059998,39.070000,18.700001,2306.548096
2022-03-18,41.200001,82.440002,16.750000,1627.000000,61.373772,84.070000,48.080002,NaN,12.72,114.680000,8.790,NaN,14.500000,NaN,31.850000,3.2320,136.160004,NaN,75.430000,191.500000,84.209999,38.990002,19.059999,2306.548096
2022-03-20,43.200001,82.440002,16.750000,1627.000000,61.373772,84.070000,48.080002,NaN,12.72,114.680000,8.790,NaN,14.500000,NaN,31.850000,3.2320,136.160004,NaN,75.430000,191.500000,84.209999,38.990002,19.059999,2306.548096
2022-03-21,42.333332,90.690002,16.090000,1758.500000,63.907227,88.959999,49.509998,NaN,13.10,114.680000,9.110,NaN,14.435000,NaN,33.450001,3.2640,142.750000,NaN,77.690002,194.710007,85.180000,40.459999,19.940001,2306.548096
2022-03-22,43.799999,89.879997,16.559999,1752.500000,63.363068,89.050003,49.860001,NaN,13.34,116.779999,9.125,NaN,14.640000,NaN,33.650002,3.2890,144.000000,NaN,76.470001,195.279999,84.199997,39.060001,19.559999,2306.548096
2022-03-23,44.599998,94.220001,16.209999,1761.000000,65.084747,90.430000,49.810001,NaN,13.09,116.150002,9.210,NaN,15.300000,NaN,33.230000,3.3140,147.139999,NaN,77.879997,194.339996,85.459999,40.130001,19.930000,2306.548096
2022-03-24,44.599998,95.059998,16.719999,1781.500000,66.253342,91.500000,51.450001,NaN,13.17,119.120003,9.350,NaN,15.300000,NaN,34.049999,3.3980,153.520004,NaN,78.300003,195.289993,88.660004,40.639999,20.020000,2306.548096
2022-03-25,44.599998,91.959999,17.010000,1735.000000,67.207848,93.019997,51.930000,NaN,13.39,115.239998,9.440,NaN,14.885000,NaN,34.560001,3.3590,157.619995,NaN,79.519997,194.929993,89.489998,40.380001,19.940001,2306.548096
2022-03-27,44.599998,91.959999,17.010000,1735.000000,67.207848,93.019997,51.930000,NaN,13.39,115.239998,9.440,NaN,14.885000,NaN,34.560001,3.3590,157.619995,NaN,79.519997,194.929993,89.489998,40.380001,19.940001,2306.548096
2022-03-28,44.466667,92.459999,17.299999,1707.000000,67.430862,92.690002,50.270000,NaN,13.14,116.360001,9.385,NaN,13.780000,NaN,33.650002,3.3560,153.850006,NaN,78.529999,190.949997,87.169998,39.900002,19.969999,2306.548096
2022-03-29,45.266666,90.070000,18.160000,1691.000000,67.466545,91.430000,50.090000,NaN,12.71,116.900002,9.230,NaN,12.940000,NaN,33.459999,3.3120,150.500000,NaN,78.379997,185.250000,84.160004,39.270000,19.950001,2306.548096
2022-03-30,44.599998,92.190002,18.049999,1706.500000,69.687782,88.389999,50.779999,NaN,13.12,115.389999,9.125,NaN,13.765000,NaN,32.860001,3.1430,149.470001,NaN,80.500000,184.679993,83.639999,40.880001,20.030001,2306.548096
2022-03-31,44.666664,90.029999,18.250000,1673.000000,68.911690,90.000000,49.740002,NaN,13.05,119.000000,9.155,NaN,14.020000,NaN,32.009998,3.1510,148.649994,NaN,80.400002,183.350006,83.430000,40.389999,19.990000,2306.548096
2022-04-01,44.666664,90.620003,18.240000,1690.500000,70.740410,90.000000,50.959999,NaN,13.37,117.510002,9.320,NaN,13.700000,NaN,32.840000,3.1108,149.259995,NaN,82.680000,184.770004,84.989998,42.189999,20.830000,2306.548096
2022-04-03,44.933334,90.620003,18.240000,1690.500000,70.740410,90.000000,50.959999,NaN,13.37,117.510002,9.320,NaN,13.700000,NaN,32.840000,3.1108,149.259995,NaN,82.680000,184.770004,84.989998,42.189999,20.830000,2306.548096
2022-04-04,44.933334,90.900002,18.230000,1699.000000,70.276543,92.500000,50.900002,NaN,13.27,118.839996,9.372,NaN,13.900000,NaN,32.669998,3.0668,149.520004,NaN,81.379997,182.199997,83.599998,40.939999,21.230000,2306.548096
2022-04-05,49.066666,87.709999,17.840000,1711.000000,68.849243,95.500000,49.090000,NaN,13.42,113.269997,9.346,NaN,14.300000,NaN,30.530001,3.0564,148.800003,NaN,80.489998,179.000000,82.540001,38.619999,20.330000,2306.548096
2022-04-06,47.733334,87.730003,17.379999,1676.000000,68.974129,94.500000,48.060001,NaN,13.47,109.709999,9.300,NaN,13.500000,NaN,30.330000,2.9656,146.490005,NaN,80.570000,178.830002,82.169998,38.470001,20.480000,2306.548096
2022-04-07,49.066666,86.099998,16.950001,1678.500000,69.000893,93.500000,48.480000,NaN,13.52,113.540001,9.322,NaN,13.150000,NaN,30.809999,2.9616,150.910004,NaN,80.849998,178.449997,83.639999,39.529999,20.480000,2306.548096
2022-04-08,49.066666,84.150002,16.590000,1707.500000,69.286354,95.500000,48.970001,NaN,13.75,111.769997,9.448,NaN,14.250000,NaN,30.610001,3.0048,150.759995,NaN,80.279999,179.360001,83.199997,41.000000,20.100000,2306.548096
2022-04-10,49.200001,84.150002,16.590000,1707.500000,69.286354,95.500000,48.970001,NaN,13.75,111.769997,9.448,NaN,14.250000,NaN,30.610001,3.0048,150.759995,NaN,80.279999,179.360001,83.199997,41.000000,20.100000,2306.548096
2022-04-11,49.533333,82.529999,16.969999,1663.000000,67.707405,93.500000,47.720001,NaN,13.47,113.650002,9.246,NaN,14.500000,NaN,31.139999,2.9948,152.800003,NaN,79.739998,183.039993,83.650002,39.619999,20.010000,2306.548096
2022-04-12,49.333332,83.260002,17.129999,1678.500000,68.715431,89.000000,48.000000,NaN,13.62,107.690002,9.454,NaN,14.250000,NaN,31.270000,2.9752,157.240005,NaN,80.489998,184.360001,84.639999,40.139999,19.930000,2306.548096
2022-04-13,46.666664,87.419998,18.950001,1667.500000,69.696701,94.500000,49.430000,NaN,13.98,107.519997,9.522,NaN,14.100000,NaN,32.720001,3.0128,163.229996,NaN,81.940002,189.169998,87.339996,43.270000,19.910000,2306.548096

---
**MXI ETF Top 25 Holdings**

*Global Materials*

In [45]:
mxi_hold = [
    "BHP", "FCX", "GLNCY", "VALE", "AAL", "NUE", "RIO",
    "GMEXICOB.MX", "FVJA.BE", "STLD", "1211.SR", "TECK", "VALT.L",
    "MT", "NPS.MU", "IZ1.BE", "ANTO.L", "BWJ0.F", "RS", "AA", "GXD.F",
    "PKX.BE", "HWHG.BE", "IPHB.F"
]

mxi_data = yf.download(mxi_hold, start=start_date, end=end_date, auto_adjust=False)

mxi_data = mxi_data['Close']

mxi_data.index = pd.to_datetime(mxi_data.index)

mxi_data.ffill(inplace=True)

[*********************100%***********************]  24 of 24 completed
ERROR:yfinance:
4 Failed downloads:
ERROR:yfinance:['FVJA.BE', 'HWHG.BE', 'PKX.BE', 'IZ1.BE']: YFTzMissingError('possibly delisted; no timezone found')

In [46]:
mxi_data.columns
mxi_data.head(100)

Ticker,1211.SR,AA,AAL,ANTO.L,BHP,BWJ0.F,FCX,FVJA.BE,GLNCY,GMEXICOB.MX,GXD.F,HWHG.BE,IPHB.F,IZ1.BE,MT,NPS.MU,NUE,PKX.BE,RIO,RS,STLD,TECK,VALE,VALT.L
Date,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,NaN,59.580002,17.959999,1338.5,53.835861,NaN,41.730000,NaN,10.08,89.290001,NaN,NaN,NaN,NaN,31.830000,NaN,114.150002,NaN,66.940002,162.220001,62.070000,28.820000,14.020000,2306.548096
2022-01-02,26.266666,59.580002,17.959999,1338.5,53.835861,NaN,41.730000,NaN,10.08,89.290001,NaN,NaN,NaN,NaN,31.830000,NaN,114.150002,NaN,66.940002,162.220001,62.070000,28.820000,14.020000,2306.548096
2022-01-03,26.133333,60.360001,18.750000,1338.5,53.826939,68.190002,41.480000,NaN,10.16,89.089996,7.125,NaN,12.535000,NaN,32.119999,2.8370,113.040001,NaN,66.730003,161.279999,61.660000,29.110001,13.810000,2306.548096
2022-01-04,26.333332,57.529999,19.020000,1369.0,54.701160,71.230003,42.150002,NaN,10.45,88.230003,7.005,NaN,12.750000,NaN,32.970001,2.8830,117.070000,NaN,67.519997,163.570007,63.520000,29.200001,13.550000,2306.548096
2022-01-05,26.366667,58.549999,18.680000,1372.0,55.352364,69.930000,41.680000,NaN,10.46,89.540001,7.160,NaN,12.865000,NaN,33.029999,2.9450,122.720001,NaN,68.709999,166.750000,65.959999,29.420000,13.660000,2306.548096
2022-01-06,26.700001,58.450001,18.570000,1328.0,55.414806,70.269997,40.529999,NaN,10.48,90.510002,6.870,NaN,12.695000,NaN,33.490002,2.9620,116.599998,NaN,70.040001,165.490005,64.050003,29.100000,14.010000,2306.548096
2022-01-07,26.700001,62.369999,19.280001,1353.0,57.413025,71.489998,41.880001,NaN,10.75,90.360001,6.875,NaN,12.310000,NaN,34.810001,3.0490,114.440002,NaN,72.239998,166.529999,62.310001,30.410000,14.810000,2306.548096
2022-01-09,27.333332,62.369999,19.280001,1353.0,57.413025,71.489998,41.880001,NaN,10.75,90.360001,6.875,NaN,12.310000,NaN,34.810001,3.0490,114.440002,NaN,72.239998,166.529999,62.310001,30.410000,14.810000,2306.548096
2022-01-10,28.299999,61.540001,18.790001,1345.5,56.333630,70.419998,41.619999,NaN,10.59,89.250000,6.940,NaN,12.345000,NaN,34.299999,3.0440,111.860001,NaN,72.709999,162.399994,60.590000,31.200001,14.650000,2306.548096
2022-01-11,28.633333,62.200001,19.020000,1342.0,57.528992,69.349998,42.990002,NaN,10.63,89.970001,6.900,NaN,13.205000,NaN,35.389999,3.0980,110.839996,NaN,74.419998,164.179993,60.970001,32.439999,15.240000,2306.548096
2022-01-12,29.400000,61.880001,18.500000,1442.5,59.901875,72.150002,45.150002,NaN,11.01,93.980003,7.665,NaN,13.285000,NaN,37.240002,3.1080,114.720001,NaN,76.070000,167.720001,63.599998,34.180000,15.550000,2306.548096
2022-01-13,29.833332,60.509998,19.340000,1435.0,59.857269,71.370003,44.330002,NaN,11.01,93.989998,7.680,NaN,13.280000,NaN,37.279999,3.2670,112.720001,NaN,75.660004,165.589996,62.820000,33.639999,15.300000,2306.548096
2022-01-14,29.833332,61.389999,18.490000,1379.0,59.741302,72.320000,44.080002,NaN,11.06,93.089996,7.460,NaN,13.390000,NaN,37.220001,3.3150,110.820000,NaN,75.400002,166.330002,62.209999,33.980000,15.380000,2306.548096
2022-01-16,30.833332,61.389999,18.490000,1379.0,59.741302,72.320000,44.080002,NaN,11.06,93.089996,7.460,NaN,13.390000,NaN,37.220001,3.3150,110.820000,NaN,75.400002,166.330002,62.209999,33.980000,15.380000,2306.548096
2022-01-17,30.333332,61.389999,18.490000,1436.5,59.741302,71.529999,44.080002,NaN,11.06,93.870003,7.445,NaN,12.705000,NaN,37.220001,3.2890,110.820000,NaN,75.400002,166.330002,62.209999,33.980000,15.380000,2306.548096
2022-01-18,29.533333,60.049999,17.900000,1439.0,59.277431,72.599998,44.290001,NaN,11.21,93.519997,7.650,NaN,12.350000,NaN,35.270000,3.0800,106.699997,NaN,75.730003,163.899994,59.900002,34.160000,15.510000,2306.548096
2022-01-19,30.733334,59.630001,17.309999,1482.5,61.088314,75.839996,44.080002,NaN,11.36,95.339996,7.675,NaN,13.325000,NaN,35.619999,2.9420,104.250000,NaN,77.919998,163.699997,58.959999,34.560001,16.180000,2306.548096
2022-01-20,31.233334,61.250000,16.760000,1464.0,60.686886,75.690002,43.189999,NaN,11.09,93.660004,7.720,NaN,13.500000,NaN,34.139999,2.9590,100.339996,NaN,76.160004,160.729996,56.959999,33.320000,15.990000,2306.548096
2022-01-21,31.233334,56.209999,16.299999,1450.0,57.957180,73.660004,40.990002,NaN,10.89,90.250000,7.475,NaN,13.220000,NaN,31.830000,2.9380,93.050003,NaN,74.360001,150.839996,52.450001,32.549999,15.600000,2306.548096
2022-01-23,30.366667,56.209999,16.299999,1450.0,57.957180,73.660004,40.990002,NaN,10.89,90.250000,7.475,NaN,13.220000,NaN,31.830000,2.9380,93.050003,NaN,74.360001,150.839996,52.450001,32.549999,15.600000,2306.548096
2022-01-24,30.299999,58.020000,16.410000,1356.5,57.636040,68.779999,39.959999,NaN,10.56,86.830002,7.215,NaN,12.455000,NaN,30.990000,2.9290,95.309998,NaN,73.269997,152.210007,54.700001,32.070000,15.310000,2306.548096
2022-01-25,30.333332,61.209999,16.459999,1379.0,56.984837,70.879997,39.630001,NaN,10.55,87.889999,7.240,NaN,13.065000,NaN,30.549999,2.8170,94.190002,NaN,73.680000,151.520004,54.119999,32.349998,15.480000,2306.548096
2022-01-26,30.333332,60.750000,16.240000,1411.5,57.511150,72.970001,38.430000,NaN,10.61,87.879997,7.290,NaN,13.495000,NaN,30.139999,2.8690,93.040001,NaN,74.029999,149.059998,53.119999,32.639999,15.530000,2306.548096
2022-01-27,30.333332,58.029999,15.780000,1391.5,58.697590,74.139999,37.099998,NaN,10.71,85.529999,7.100,NaN,13.210000,NaN,28.680000,2.8250,96.739998,NaN,75.089996,150.600006,54.340000,31.889999,15.570000,2306.548096
2022-01-28,30.333332,57.400002,15.640000,1337.5,57.243534,71.320000,36.040001,NaN,10.53,86.550003,7.310,NaN,12.940000,NaN,29.160000,2.7700,99.790001,NaN,73.129997,151.589996,54.919998,30.709999,15.580000,2306.548096
2022-01-30,30.666666,57.400002,15.640000,1337.5,57.243534,71.320000,36.040001,NaN,10.53,86.550003,7.310,NaN,12.940000,NaN,29.160000,2.7700,99.790001,NaN,73.129997,151.589996,54.919998,30.709999,15.580000,2306.548096
2022-01-31,30.633333,56.709999,16.469999,1332.5,56.735058,70.370003,37.220001,NaN,10.37,88.589996,7.320,NaN,13.940000,NaN,29.660000,2.8420,101.400002,NaN,71.400002,152.880005,55.520000,30.870001,15.180000,2306.548096
2022-02-01,30.700001,58.169998,16.830000,1361.5,58.001785,72.830002,39.020000,NaN,10.77,89.830002,7.480,NaN,13.025000,NaN,31.490000,2.8020,107.459999,NaN,74.199997,158.460007,57.610001,32.490002,16.180000,2306.548096
2022-02-02,30.866667,59.209999,16.959999,1284.0,58.447815,73.489998,39.389999,NaN,10.86,90.139999,7.645,NaN,13.295000,NaN,31.790001,2.9070,111.980003,NaN,74.290001,160.050003,59.169998,32.380001,16.350000,2306.548096
2022-02-03,30.666666,62.740002,16.570000,1258.5,58.644070,73.199997,38.200001,NaN,10.80,87.279999,7.295,NaN,13.000000,NaN,31.480000,2.8630,112.250000,NaN,73.470001,159.750000,58.869999,32.660000,16.150000,2306.548096
2022-02-04,30.666666,64.220001,16.450001,1227.0,59.018734,72.669998,38.419998,NaN,10.92,88.870003,7.260,NaN,12.750000,NaN,31.469999,2.9070,111.260002,NaN,73.889999,156.139999,58.939999,33.230000,16.549999,2306.548096
2022-02-06,31.033333,64.220001,16.450001,1227.0,59.018734,72.669998,38.419998,NaN,10.92,88.870003,7.260,NaN,12.750000,NaN,31.469999,2.9070,111.260002,NaN,73.889999,156.139999,58.939999,33.230000,16.549999,2306.548096
2022-02-07,31.233334,63.750000,17.280001,1233.5,61.061550,74.330002,38.900002,NaN,11.06,88.870003,7.440,NaN,13.335000,NaN,32.389999,2.9480,111.120003,NaN,76.639999,154.039993,58.330002,34.160000,17.170000,2306.548096
2022-02-08,30.966665,69.970001,18.260000,1242.0,61.694916,74.080002,40.630001,NaN,11.29,91.190002,7.700,NaN,13.090000,NaN,33.619999,3.0100,115.570000,NaN,78.099998,159.009995,60.599998,34.939999,17.430000,2306.548096
2022-02-09,31.333332,71.910004,18.760000,1290.0,61.462978,75.150002,43.560001,NaN,11.37,93.510002,8.140,NaN,13.500000,NaN,34.299999,3.0810,120.080002,NaN,78.330002,163.149994,62.549999,35.950001,17.510000,2306.548096
2022-02-10,31.333332,71.169998,18.709999,1344.5,62.390724,74.620003,43.910000,NaN,11.28,97.989998,8.460,NaN,13.795000,NaN,33.200001,3.1030,121.589996,NaN,78.959999,160.869995,61.340000,36.099998,17.850000,2306.548096
2022-02-11,31.333332,73.519997,17.610001,1366.5,61.471901,75.199997,42.799999,NaN,11.16,101.290001,8.335,NaN,13.530000,NaN,30.690001,3.1000,118.410004,NaN,77.790001,160.869995,60.709999,36.430000,17.540001,2306.548096
2022-02-13,30.833332,73.519997,17.610001,1366.5,61.471901,75.199997,42.799999,NaN,11.16,101.290001,8.335,NaN,13.530000,NaN,30.690001,3.1000,118.410004,NaN,77.790001,160.869995,60.709999,36.430000,17.540001,2306.548096
2022-02-14,31.166666,73.860001,17.430000,1389.5,60.892059,76.110001,42.450001,NaN,11.44,102.180000,7.810,NaN,14.000000,NaN,29.730000,3.0860,117.349998,NaN,78.370003,161.850006,61.610001,35.799999,17.490000,2306.548096
2022-02-15,31.133333,74.040001,18.840000,1385.5,60.231937,73.040001,43.669998,NaN,11.55,104.610001,8.305,NaN,13.505000,NaN,30.809999,2.9980,121.580002,NaN,77.129997,166.699997,63.779999,36.000000,17.139999,2306.548096
2022-02-16,31.900000,77.839996,18.820000,1403.0,61.311329,74.120003,44.250000,NaN,11.56,105.849998,8.375,NaN,14.015000,NaN,31.760000,3.0680,122.660004,NaN,78.559998,168.199997,64.290001,36.220001,17.440001,2306.548096
2022-02-17,33.000000,76.470001,18.219999,1373.0,60.588760,73.940002,43.209999,NaN,11.37,99.970001,8.255,NaN,14.680000,NaN,30.459999,3.0520,120.940002,NaN,76.680000,173.740005,63.240002,35.980000,16.600000,2306.548096
2022-02-18,33.000000,78.199997,17.870001,1404.0,61.855488,75.419998,43.020000,NaN,11.41,98.449997,8.335,NaN,14.655000,NaN,30.330000,3.0890,122.930000,NaN,77.629997,174.949997,63.950001,35.490002,16.639999,2306.548096
2022-02-20,31.966665,78.199997,17.870001,1404.0,61.855488,75.419998,43.020000,NaN,11.41,98.449997,8.335,NaN,14.655000,NaN,30.330000,3.0890,122.930000,NaN,77.629997,174.949997,63.950001,35.490002,16.639999,2306.548096
2022-02-21,32.700001,78.199997,17.870001,1396.0,61.855488,73.360001,43.020000,NaN,11.41,96.720001,7.815,NaN,14.200000,NaN,30.330000,3.1440,122.930000,NaN,77.629997,174.949997,63.950001,35.490002,16.639999,2306.548096
2022-02-22,32.700001,74.089996,17.430000,1405.5,61.320251,73.820000,42.360001,NaN,11.42,98.750000,7.760,NaN,14.990000,NaN,30.200001,3.0860,118.709999,NaN,77.769997,174.649994,63.040001,35.529999,17.180000,2306.548096
2022-02-23,32.599998,75.320000,16.639999,1439.5,61.338093,73.980003,42.459999,NaN,11.55,97.809998,7.940,NaN,14.995000,NaN,29.719999,3.0700,117.980003,NaN,77.500000,172.669998,62.160000,35.450001,17.270000,2306.548096
2022-02-24,33.233334,73.300003,16.959999,1370.5,56.645851,72.790001,43.720001,NaN,11.45,101.809998,7.520,NaN,15.975000,NaN,28.350000,3.0980,120.900002,NaN,75.419998,172.979996,63.259998,34.840000,17.070000,2306.548096
2022-02-25,33.233334,77.849998,17.459999,1447.5,59.821587,77.500000,46.340000,NaN,11.91,101.919998,7.890,NaN,15.950000,NaN,31.650000,3.1190,130.050003,NaN,77.959999,183.419998,69.010002,36.840000,17.820000,2306.548096
2022-02-27,34.799999,77.849998,17.459999,1447.5,59.821587,77.500000,46.340000,NaN,11.91,101.919998,7.890,NaN,15.950000,NaN,31.650000,3.1190,130.050003,NaN,77.959999,183.419998,69.010002,36.840000,17.820000,2306.548096
2022-02-28,35.599998,75.339996,17.250000,1521.0,60.472794,77.730003,46.950001,NaN,11.72,105.070000,8.095,NaN,16.170000,NaN,30.940001,3.2320,131.619995,NaN,78.580002,190.869995,70.580002,35.950001,18.490000,2306.548096
2022-03-01,35.933334,79.779999,16.290001,1571.5,61.106155,77.760002,47.910000,NaN,11.82,108.349998,8.595,NaN,16.834999,NaN,31.500000,3.2780,131.000000,NaN,80.029999,187.179993,72.169998,36.900002,18.860001,2306.548096
2022-03-02,37.133331,82.559998,16.370001,1576.5,64.201607,88.500000,48.160000,NaN,12.15,109.419998,8.920,NaN,17.299999,NaN,32.889999,3.3200,138.009995,NaN,83.540001,189.210007,75.230003,38.709999,19.469999,2306.548096
2022-03-03,39.599998,82.889999,15.710000,1541.0,65.120430,87.019997,49.090000,NaN,12.80,115.699997,8.880,NaN,16.455000,NaN,32.209999,3.3780,137.529999,NaN,84.000000,190.029999,77.089996,40.139999,19.840000,2306.548096
2022-03-04,39.599998,90.660004,14.590000,1532.0,65.227478,83.300003,50.110001,NaN,12.28,116.980003,9.275,NaN,16.875000,NaN,29.340000,3.3780,138.720001,NaN,81.879997,188.860001,77.379997,41.490002,20.150000,2306.548096
2022-03-06,40.733334,90.660004,14.590000,1532.0,65.227478,83.300003,50.110001,NaN,12.28,116.980003,9.275,NaN,16.875000,NaN,29.340000,3.3780,138.720001,NaN,81.879997,188.860001,77.379997,41.490002,20.150000,2306.548096
2022-03-07,43.333332,85.400002,12.840000,1545.5,64.585190,81.980003,47.150002,NaN,12.47,117.199997,9.140,NaN,16.280001,NaN,27.959999,3.3780,131.899994,NaN,79.540001,184.690002,72.379997,39.200001,20.600000,2306.548096
2022-03-08,42.666664,82.370003,13.510000,1518.0,62.060661,82.519997,46.669998,NaN,12.41,117.290001,9.110,NaN,15.805000,NaN,28.660000,3.2150,125.959999,NaN,77.529999,182.009995,69.970001,38.779999,19.820000,2306.548096
2022-03-09,41.333332,79.519997,14.300000,1498.0,62.301517,78.449997,46.990002,NaN,12.34,114.419998,9.140,NaN,14.950000,NaN,30.010000,3.1090,130.009995,NaN,77.720001,189.009995,71.949997,40.090000,18.719999,2306.548096
2022-03-10,40.599998,82.940002,14.200000,1568.0,63.523640,77.620003,47.709999,NaN,13.24,115.570000,9.000,NaN,15.510000,NaN,30.020000,3.1920,133.559998,NaN,74.849998,188.270004,72.389999,42.279999,19.309999,2306.548096
2022-03-11,40.599998,79.040001,14.020000,1576.0,61.150757,80.339996,46.930000,NaN,13.19,113.680000,9.130,NaN,14.750000,NaN,29.820000,3.2390,135.250000,NaN,72.720001,188.229996,72.120003,41.860001,19.070000,2306.548096
2022-03-13,40.866665,79.040001,14.020000,1576.0,61.150757,80.339996,46.930000,NaN,13.19,113.680000,9.130,NaN,14.750000,NaN,29.820000,3.2390,135.250000,NaN,72.720001,188.229996,72.120003,41.860001,19.070000,2306.548096
2022-03-14,39.733334,73.500000,14.250000,1556.0,58.421055,79.400002,44.520000,NaN,12.34,108.410004,8.845,NaN,14.160000,NaN,30.010000,3.2920,132.050003,NaN,69.370003,187.669998,71.489998,38.349998,17.799999,2306.548096
2022-03-15,37.000000,73.709999,15.570000,1531.0,57.787689,80.000000,44.279999,NaN,11.96,104.589996,8.235,NaN,14.310000,NaN,30.129999,3.1700,135.520004,NaN,69.080002,190.039993,73.110001,37.709999,17.240000,2306.548096
2022-03-16,40.666664,75.629997,16.469999,1632.5,59.625336,83.330002,46.419998,NaN,12.61,103.339996,8.355,NaN,13.700000,NaN,32.040001,3.2820,135.110001,NaN,72.720001,189.470001,75.010002,37.529999,17.750000,2306.548096
2022-03-17,41.200001,80.730003,16.549999,1666.0,60.570919,82.889999,48.590000,NaN,12.49,109.459999,8.740,NaN,14.445000,NaN,31.990000,3.2280,134.929993,NaN,74.839996,191.029999,81.059998,39.070000,18.700001,2306.548096
2022-03-18,41.200001,82.440002,16.750000,1627.0,61.373772,84.070000,48.080002,NaN,12.72,114.680000,8.790,NaN,14.500000,NaN,31.850000,3.2320,136.160004,NaN,75.430000,191.500000,84.209999,38.990002,19.059999,2306.548096
2022-03-20,43.200001,82.440002,16.750000,1627.0,61.373772,84.070000,48.080002,NaN,12.72,114.680000,8.790,NaN,14.500000,NaN,31.850000,3.2320,136.160004,NaN,75.430000,191.500000,84.209999,38.990002,19.059999,2306.548096
2022-03-21,42.333332,90.690002,16.090000,1758.5,63.907227,88.959999,49.509998,NaN,13.10,114.680000,9.110,NaN,14.435000,NaN,33.450001,3.2640,142.750000,NaN,77.690002,194.710007,85.180000,40.459999,19.940001,2306.548096
2022-03-22,43.799999,89.879997,16.559999,1752.5,63.363068,89.050003,49.860001,NaN,13.34,116.779999,9.125,NaN,14.640000,NaN,33.650002,3.2890,144.000000,NaN,76.470001,195.279999,84.199997,39.060001,19.559999,2306.548096
2022-03-23,44.599998,94.220001,16.209999,1761.0,65.084747,90.430000,49.810001,NaN,13.09,116.150002,9.210,NaN,15.300000,NaN,33.230000,3.3140,147.139999,NaN,77.879997,194.339996,85.459999,40.130001,19.930000,2306.548096
2022-03-24,44.599998,95.059998,16.719999,1781.5,66.253342,91.500000,51.450001,NaN,13.17,119.120003,9.350,NaN,15.300000,NaN,34.049999,3.3980,153.520004,NaN,78.300003,195.289993,88.660004,40.639999,20.020000,2306.548096
2022-03-25,44.599998,91.959999,17.010000,1735.0,67.207848,93.019997,51.930000,NaN,13.39,115.239998,9.440,NaN,14.885000,NaN,34.560001,3.3590,157.619995,NaN,79.519997,194.929993,89.489998,40.380001,19.940001,2306.548096
2022-03-27,44.599998,91.959999,17.010000,1735.0,67.207848,93.019997,51.930000,NaN,13.39,115.239998,9.440,NaN,14.885000,NaN,34.560001,3.3590,157.619995,NaN,79.519997,194.929993,89.489998,40.380001,19.940001,2306.548096
2022-03-28,44.466667,92.459999,17.299999,1707.0,67.430862,92.690002,50.270000,NaN,13.14,116.360001,9.385,NaN,13.780000,NaN,33.650002,3.3560,153.850006,NaN,78.529999,190.949997,87.169998,39.900002,19.969999,2306.548096
2022-03-29,45.266666,90.070000,18.160000,1691.0,67.466545,91.430000,50.090000,NaN,12.71,116.900002,9.230,NaN,12.940000,NaN,33.459999,3.3120,150.500000,NaN,78.379997,185.250000,84.160004,39.270000,19.950001,2306.548096
2022-03-30,44.599998,92.190002,18.049999,1706.5,69.687782,88.389999,50.779999,NaN,13.12,115.389999,9.125,NaN,13.765000,NaN,32.860001,3.1430,149.470001,NaN,80.500000,184.679993,83.639999,40.880001,20.030001,2306.548096
2022-03-31,44.666664,90.029999,18.250000,1673.0,68.911690,90.000000,49.740002,NaN,13.05,119.000000,9.155,NaN,14.020000,NaN,32.009998,3.1510,148.649994,NaN,80.400002,183.350006,83.430000,40.389999,19.990000,2306.548096
2022-04-01,44.666664,90.620003,18.240000,1690.5,70.740410,90.000000,50.959999,NaN,13.37,117.510002,9.320,NaN,13.700000,NaN,32.840000,3.1108,149.259995,NaN,82.680000,184.770004,84.989998,42.189999,20.830000,2306.548096
2022-04-03,44.933334,90.620003,18.240000,1690.5,70.740410,90.000000,50.959999,NaN,13.37,117.510002,9.320,NaN,13.700000,NaN,32.840000,3.1108,149.259995,NaN,82.680000,184.770004,84.989998,42.189999,20.830000,2306.548096
2022-04-04,44.933334,90.900002,18.230000,1699.0,70.276543,92.500000,50.900002,NaN,13.27,118.839996,9.372,NaN,13.900000,NaN,32.669998,3.0668,149.520004,NaN,81.379997,182.199997,83.599998,40.939999,21.230000,2306.548096
2022-04-05,49.066666,87.709999,17.840000,1711.0,68.849243,95.500000,49.090000,NaN,13.42,113.269997,9.346,NaN,14.300000,NaN,30.530001,3.0564,148.800003,NaN,80.489998,179.000000,82.540001,38.619999,20.330000,2306.548096
2022-04-06,47.733334,87.730003,17.379999,1676.0,68.974129,94.500000,48.060001,NaN,13.47,109.709999,9.300,NaN,13.500000,NaN,30.330000,2.9656,146.490005,NaN,80.570000,178.830002,82.169998,38.470001,20.480000,2306.548096
2022-04-07,49.066666,86.099998,16.950001,1678.5,69.000893,93.500000,48.480000,NaN,13.52,113.540001,9.322,NaN,13.150000,NaN,30.809999,2.9616,150.910004,NaN,80.849998,178.449997,83.639999,39.529999,20.480000,2306.548096
2022-04-08,49.066666,84.150002,16.590000,1707.5,69.286354,95.500000,48.970001,NaN,13.75,111.769997,9.448,NaN,14.250000,NaN,30.610001,3.0048,150.759995,NaN,80.279999,179.360001,83.199997,41.000000,20.100000,2306.548096
2022-04-10,49.200001,84.150002,16.590000,1707.5,69.286354,95.500000,48.970001,NaN,13.75,111.769997,9.448,NaN,14.250000,NaN,30.610001,3.0048,150.759995,NaN,80.279999,179.360001,83.199997,41.000000,20.100000,2306.548096
2022-04-11,49.533333,82.529999,16.969999,1663.0,67.707405,93.500000,47.720001,NaN,13.47,113.650002,9.246,NaN,14.500000,NaN,31.139999,2.9948,152.800003,NaN,79.739998,183.039993,83.650002,39.619999,20.010000,2306.548096
2022-04-12,49.333332,83.260002,17.129999,1678.5,68.715431,89.000000,48.000000,NaN,13.62,107.690002,9.454,NaN,14.250000,NaN,31.270000,2.9752,157.240005,NaN,80.489998,184.360001,84.639999,40.139999,19.930000,2306.548096
2022-04-13,46.666664,87.419998,18.950001,1667.5,69.696701,94.500000,49.430000,NaN,13.98,107.519997,9.522,NaN,14.100000,NaN,32.720001,3.0128,163.229996,NaN,81.940002,189.169998,87.339996,43.270000,19.910000,2306.548096
2022-04-14,46.933334,87.769997,19.000000,1676.5,69.714539,95.500000,49.189999,NaN,13.76,107.519997,9.614,NaN,13.750000,NaN,33.009998,3.0660,165.320007,NaN,81.870003,194.259995,88.320000,43.160000,19.480000,2306.548096
2022-04-17,46.200001,87.769997,19.000000,1676.5,69.714539,95.500000,49.189999,NaN,13.76,107.519997,9.614,NaN,13.750000,NaN,33.009998,3.0660,165.320007,NaN,81.870003,194.259995,88.320000,43.160000,19.480000,2306.548096

---
**FUTY ETF Top 25 Holdings**

*Broad Utilities Index*

In [47]:
futy_hold = [
    "NEE", "CEG", "SO", "DUK", "AEP", "SRE", "VST", "D", "EXC", "XEL",
    "ETR", "PEG", "ED", "PCG", "WEC", "NRG", "AEE", "ATO", "DTE", "PPL",
    "AWK", "CNP", "FE", "ES", "EIX"
]

futy_data = yf.download(futy_hold, start=start_date, end=end_date, auto_adjust=False)

futy_data = futy_data['Close']

futy_data.index = pd.to_datetime(futy_data.index)

futy_data.ffill(inplace=True)

[*********************100%***********************]  25 of 25 completed

In [48]:
futy_data.columns
futy_data.head(10)

Ticker,AEE,AEP,ATO,AWK,CEG,CNP,D,DTE,DUK,ED,EIX,ES,ETR,EXC,FE,NEE,NRG,PCG,PEG,PPL,SO,SRE,VST,WEC,XEL
Date,,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,89.010002,88.970001,104.769997,188.860001,NaN,27.910000,78.559998,119.540001,104.900002,85.320000,68.250000,90.980003,56.325001,41.198288,41.590000,93.360001,43.080002,12.14,66.730003,30.059999,68.580002,66.139999,22.770000,97.070000,67.699997
2022-01-03,88.580002,88.610001,105.010002,184.139999,NaN,27.620001,78.349998,119.180000,103.489998,85.129997,67.510002,89.129997,55.700001,40.706135,41.240002,91.660004,42.959999,12.21,66.160004,30.139999,68.169998,65.995003,22.740000,96.089996,67.940002
2022-01-04,88.110001,88.650002,106.260002,179.419998,NaN,27.450001,78.099998,119.379997,103.410004,84.970001,66.669998,88.389999,55.639999,40.663338,41.080002,90.680000,42.619999,12.44,65.989998,29.990000,68.169998,67.184998,22.520000,95.849998,68.370003
2022-01-05,88.330002,89.470001,106.599998,178.100006,NaN,27.389999,79.209999,119.250000,103.639999,85.550003,65.199997,89.230003,55.770000,40.634808,40.799999,89.730003,41.419998,11.86,65.830002,30.049999,68.250000,67.595001,22.110001,96.959999,69.040001
2022-01-06,87.900002,89.180000,105.769997,175.300003,NaN,27.650000,79.059998,119.570000,103.470001,85.370003,64.620003,88.900002,54.825001,40.463623,40.939999,85.769997,40.639999,11.82,65.889999,30.010000,68.169998,68.080002,22.320000,96.349998,68.500000
2022-01-07,88.239998,90.800003,105.290001,173.500000,NaN,27.660000,80.209999,119.690002,104.500000,85.669998,65.000000,89.660004,56.064999,40.399429,41.410000,86.410004,40.560001,12.21,67.000000,30.250000,68.639999,69.105003,22.709999,97.209999,69.099998
2022-01-10,87.510002,90.500000,105.150002,170.029999,NaN,27.690001,79.830002,120.150002,104.559998,84.779999,65.639999,88.989998,55.849998,40.527817,41.520000,84.290001,40.380001,12.23,66.260002,30.230000,68.529999,68.849998,22.459999,96.900002,69.860001
2022-01-11,86.970001,89.769997,104.639999,168.309998,NaN,27.400000,79.129997,118.779999,103.230003,83.070000,64.360001,86.629997,54.369999,39.671898,41.360001,84.790001,40.880001,12.17,65.849998,29.950001,67.650002,67.919998,22.510000,95.320000,68.599998
2022-01-12,87.709999,90.290001,104.199997,169.179993,NaN,27.420000,79.320000,119.209999,103.620003,83.190002,64.430000,87.489998,54.619999,39.935806,41.410000,85.089996,41.330002,12.51,66.040001,29.959999,67.779999,68.110001,22.930000,95.699997,68.589996
2022-01-13,88.860001,90.860001,105.989998,168.089996,NaN,27.549999,79.750000,119.830002,104.150002,83.940002,64.070000,88.070000,55.320000,40.292439,41.590000,84.900002,40.900002,12.75,66.300003,30.000000,68.349998,68.440002,22.610001,97.279999,69.019997

---
**PAVE ETF Top 25 Holdings**

*Global Infrastructure Development*

In [49]:
pave_hold = [
    "HWM", "PH", "PWR", "CRH", "URI", "NSC", "EMR", "ROK", "FAST",
    "SRE", "CSX", "DE", "TT", "UNP", "NUE", "VMC", "MLM", "ETN",
    "EME", "STLD", "HUBB", "TRMB", "WWD", "FTV", "MTZ"
]

pave_data = yf.download(pave_hold, start=start_date, end=end_date, auto_adjust=False)

pave_data = pave_data['Close']

pave_data.index = pd.to_datetime(pave_data.index)

pave_data.ffill(inplace=True)

[*********************100%***********************]  25 of 25 completed

In [50]:
pave_data.columns
pave_data.head(10)

Ticker,CRH,CSX,DE,EME,EMR,ETN,FAST,FTV,HUBB,HWM,MLM,MTZ,NSC,NUE,PH,PWR,ROK,SRE,STLD,TRMB,TT,UNP,URI,VMC,WWD
Date,,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,52.799999,37.599998,342.890015,127.389999,92.970001,172.820007,32.029999,57.490582,208.270004,31.830000,440.519989,92.279999,297.709991,114.150002,318.119995,114.660004,348.850006,66.139999,62.070000,87.190002,202.029999,251.929993,332.290009,207.580002,109.459999
2022-01-03,53.200001,37.080002,350.109985,127.360001,91.760002,168.660004,30.990000,55.440845,205.289993,32.330002,439.010010,94.180000,292.350006,113.040001,316.000000,112.269997,339.660004,65.995003,61.660000,86.680000,194.850006,247.770004,330.640015,207.899994,110.480003
2022-01-04,54.230000,37.630001,371.290009,130.009995,95.830002,171.460007,31.165001,55.666920,209.500000,33.529999,441.510010,96.080002,294.720001,117.070000,324.040009,116.150002,343.100006,67.184998,63.520000,85.110001,195.000000,252.029999,347.089996,210.529999,112.650002
2022-01-05,53.349998,37.439999,372.049988,127.099998,95.690002,169.009995,30.770000,54.491333,204.229996,33.320000,437.170013,94.080002,294.709991,122.720001,318.369995,109.320000,337.359985,67.595001,65.959999,81.610001,192.669998,252.789993,335.019989,208.479996,110.389999
2022-01-06,52.950001,37.709999,376.359985,127.860001,96.230003,169.410004,30.945000,54.596836,204.309998,33.650002,437.089996,94.480003,296.640015,116.599998,324.130005,109.989998,335.109985,68.080002,64.050003,82.029999,195.029999,253.490005,335.170013,209.949997,110.419998
2022-01-07,52.959999,37.509998,378.649994,125.570000,95.690002,167.850006,30.315001,54.220043,200.039993,34.009998,429.200012,93.959999,296.809998,114.440002,323.739990,106.690002,327.880005,69.105003,62.310001,79.139999,189.270004,254.779999,325.980011,207.919998,112.040001
2022-01-10,52.259998,36.540001,379.859985,123.839996,95.300003,166.419998,30.084999,54.325546,196.320007,33.980000,416.250000,94.750000,287.970001,111.860001,317.450012,107.769997,330.149994,68.849998,60.590000,78.769997,190.139999,250.279999,322.209991,200.080002,110.550003
2022-01-11,53.360001,36.299999,380.549988,124.660004,96.379997,167.759995,30.145000,55.327808,200.330002,33.919998,419.329987,96.570000,286.420013,110.839996,321.369995,109.980003,335.000000,67.919998,60.970001,79.489998,193.479996,246.419998,333.989990,200.440002,113.449997
2022-01-12,54.070000,36.639999,376.250000,123.099998,96.919998,171.460007,30.190001,55.576488,202.399994,33.910000,422.570007,93.919998,288.179993,114.720001,325.109985,110.139999,335.100006,68.110001,63.599998,79.160004,195.240005,247.000000,331.950012,202.880005,113.930000
2022-01-13,53.970001,36.740002,380.390015,124.849998,97.279999,171.179993,30.375000,55.410702,200.110001,34.380001,410.890015,94.470001,290.059998,112.720001,327.790009,107.279999,330.010010,68.440002,62.820000,75.940002,188.000000,247.619995,336.209991,199.070007,115.220001

---
**TAN ETF Top 25 Holdings**

*Solar Producer and Suppliers*

In [51]:
tan_hold = [
    "NXT", "FSLR", "ENPH", "RUN", "GCPEF", "ENLT", "SEDG", "XNYIF",
    "HASI", "AOR.BE", "DQ", "CWEN", "SHLS", "ARRY", "DORL.TA", "CSIQ",
    "NOFR.TA", "JKS", "GRE.MC", "ENRG.TA", "66T.BE", "S93.BE", "FGSGF", "6443.TW"
]

tan_data = yf.download(tan_hold, start=start_date, end=end_date, auto_adjust=False)

tan_data = tan_data['Close']

tan_data.index = pd.to_datetime(tan_data.index)

tan_data.ffill(inplace=True)

[*********************100%***********************]  24 of 24 completed
ERROR:yfinance:
3 Failed downloads:
ERROR:yfinance:['66T.BE', 'AOR.BE', 'S93.BE']: YFTzMissingError('possibly delisted; no timezone found')

In [52]:
tan_data.columns
tan_data.head(10)

Ticker,6443.TW,66T.BE,AOR.BE,ARRY,CSIQ,CWEN,DORL.TA,DQ,ENLT,ENPH,ENRG.TA,FGSGF,FSLR,GCPEF,GRE.MC,HASI,JKS,NOFR.TA,NXT,RUN,S93.BE,SEDG,SHLS,XNYIF
Date,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,NaN,NaN,NaN,15.69,31.290001,36.029999,NaN,40.320000,NaN,182.940002,NaN,4.43,87.160004,0.297619,NaN,53.119999,45.959999,NaN,NaN,34.299999,NaN,280.570007,24.299999,1.660
2022-01-03,41.327625,NaN,NaN,15.91,31.330000,35.959999,1401.0,41.970001,NaN,184.449997,1340.0,4.43,88.580002,0.297619,29.299999,54.060001,46.369999,9640.0,NaN,35.470001,NaN,282.450012,23.840000,1.684
2022-01-04,42.310448,NaN,NaN,14.97,31.170000,35.389999,1425.0,42.009998,NaN,178.279999,1350.0,4.43,87.279999,0.297619,28.850000,53.639999,46.189999,9500.0,NaN,34.570000,NaN,273.100006,22.549999,1.660
2022-01-05,41.278484,NaN,NaN,13.92,29.160000,33.970001,1470.0,39.990002,NaN,157.199997,1334.0,4.43,83.510002,0.248016,28.700001,49.860001,43.560001,9607.0,NaN,31.420000,NaN,249.809998,21.320000,1.541
2022-01-06,40.197384,NaN,NaN,13.84,29.170000,34.160000,1410.0,39.869999,NaN,151.490005,1288.0,4.43,83.970001,0.347222,27.049999,49.419998,43.180000,9151.0,NaN,31.480000,NaN,248.240005,21.120001,1.532
2022-01-07,39.558548,NaN,NaN,14.12,29.780001,33.860001,1410.0,40.090000,NaN,145.130005,1288.0,4.43,84.680000,0.277778,27.100000,49.000000,44.650002,9151.0,NaN,31.719999,NaN,248.910004,21.870001,1.532
2022-01-10,40.049957,NaN,NaN,14.01,29.100000,33.150002,1341.0,39.580002,NaN,147.130005,1301.0,4.43,84.300003,0.297619,26.900000,47.889999,44.689999,8800.0,NaN,31.520000,NaN,255.470001,21.530001,1.605
2022-01-11,40.393948,NaN,NaN,14.41,29.510000,33.610001,1360.0,39.599998,NaN,148.509995,1338.0,4.43,84.449997,0.347222,27.500000,48.720001,45.570000,8883.0,NaN,32.730000,NaN,261.089996,22.780001,1.605
2022-01-12,40.049957,NaN,NaN,14.25,29.719999,33.419998,1387.0,41.740002,NaN,149.279999,1310.0,4.43,84.120003,0.317460,27.400000,48.560001,46.049999,8950.0,NaN,33.250000,NaN,261.019989,22.990000,1.600
2022-01-13,39.509407,NaN,NaN,13.47,27.760000,33.000000,1387.0,41.220001,NaN,143.490005,1290.0,4.20,82.779999,0.297619,28.150000,46.200001,45.270000,8826.0,NaN,32.759998,NaN,260.429993,21.860001,1.520

---
**DTCR ETF Top 25 Holdings**

*Data Center Real Estate and Infrastructure*

In [53]:
dtcr_hold = [
    "APLD", "EQIX", "DLR", "2344.TW", "AMT", "CCI", "MU", "GDS",
    "AJBU.SI", "000660.KS", "VNET", "NXT", "INTC", "0788.HK", "SBAC",
    "AMD", "AVGO", "MRVL", "3006.TW", "NVDA", "UNIT", "MCHP",
    "ARM", "SMCI", "1686.HK"
]

dtcr_data = yf.download(dtcr_hold, start=start_date, end=end_date, auto_adjust=False)

dtcr_data = dtcr_data['Close']

dtcr_data.index = pd.to_datetime(dtcr_data.index)

dtcr_data.ffill(inplace=True)

[*********************100%***********************]  25 of 25 completed

In [54]:
dtcr_data.columns
dtcr_data.head(10)

Ticker,000660.KS,0788.HK,1686.HK,2344.TW,3006.TW,AJBU.SI,AMD,AMT,APLD,ARM,AVGO,CCI,DLR,EQIX,GDS,INTC,MCHP,MRVL,MU,NVDA,NXT,SBAC,SMCI,UNIT,VNET
Date,,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,NaN,8.6,7.38,NaN,NaN,2.47,143.899994,292.500000,NaN,NaN,66.541000,208.740005,176.869995,845.840027,47.160000,51.500000,87.059998,87.489998,93.150002,29.410999,NaN,389.019989,4.395,23.272425,9.03
2022-01-03,NaN,8.5,7.28,31.822126,164.5,2.47,150.240005,286.380005,NaN,NaN,66.332001,207.740005,175.089996,836.109985,45.380001,53.209999,88.000000,89.430000,95.750000,30.121000,NaN,379.869995,4.562,23.073090,9.01
2022-01-04,128500.0,8.8,7.24,31.425591,161.5,2.45,144.419998,282.769989,NaN,NaN,67.092003,202.149994,169.089996,814.630005,41.020000,53.139999,87.470001,88.370003,96.339996,29.290001,NaN,369.459991,4.714,22.325581,8.37
2022-01-05,125500.0,8.9,7.03,31.029053,158.0,2.43,136.149994,264.570007,NaN,NaN,64.300003,188.460007,162.880005,789.099976,39.070000,53.869999,84.519997,84.120003,94.400002,27.604000,NaN,350.769989,4.536,21.860464,8.24
2022-01-06,125000.0,9.0,7.31,30.384680,155.0,2.39,136.229996,264.890015,NaN,NaN,63.702999,192.500000,160.800003,775.080017,41.849998,54.009998,85.300003,85.529999,95.650002,28.177999,NaN,349.170013,4.510,21.578074,8.37
2022-01-07,127000.0,9.2,7.14,30.037708,148.5,2.36,132.000000,266.579987,NaN,NaN,61.915001,194.729996,161.059998,774.940002,42.900002,53.439999,81.930000,83.110001,94.449997,27.247000,NaN,347.910004,4.408,21.661131,8.74
2022-01-10,124500.0,9.2,7.19,30.384680,152.0,2.32,132.000000,264.410004,NaN,NaN,62.116001,190.669998,159.240005,764.330017,44.740002,55.209999,82.930000,82.209999,93.889999,27.400000,NaN,342.579987,4.418,21.378738,9.18
2022-01-11,128000.0,8.9,7.21,29.740307,145.0,2.30,137.309998,260.489990,NaN,NaN,62.205002,187.589996,159.029999,766.880005,46.230000,55.910000,84.610001,86.230003,94.199997,27.816999,NaN,341.690002,4.491,21.345514,9.19
2022-01-12,128500.0,9.1,7.28,29.839439,148.5,2.30,137.470001,259.390015,NaN,NaN,62.200001,189.419998,158.949997,764.460022,46.290001,55.740002,85.230003,84.940002,95.110001,27.999001,NaN,338.510010,4.484,21.212626,9.28
2022-01-13,129500.0,9.1,7.28,29.839439,144.5,2.32,132.740005,255.440002,NaN,NaN,59.719002,187.380005,157.619995,748.119995,42.590000,54.939999,83.690002,78.650002,95.620003,26.575001,NaN,334.179993,4.529,20.930233,8.99

---
**VOLT ETF Top 25 Holdings**

*Data Center Electricity Demand*

In [55]:
volt_hold = [
    "NEE", "POWL", "BELFB", "APH", "PWR", "HUBB", "AEP", "ET",
    "NI", "IDA", "ETR", "GEV", "ITRI", "OGE", "SU", "JCI",
    "ABJA.MU", "ETN", "BWXT", "NVT", "XEL", "VRT", "CAT", "PPL",
    "AEIS"
]

volt_data = yf.download(volt_hold, start=start_date, end=end_date, auto_adjust=False)

volt_data = volt_data['Close']

volt_data.index = pd.to_datetime(volt_data.index)

volt_data.ffill(inplace=True)

[*********************100%***********************]  25 of 25 completed

In [56]:
volt_data.columns
volt_data.head(10)

Ticker,ABJA.MU,AEIS,AEP,APH,BELFB,BWXT,CAT,ET,ETN,ETR,GEV,HUBB,IDA,ITRI,JCI,NEE,NI,NVT,OGE,POWL,PPL,PWR,SU,VRT,XEL
Date,,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,NaN,91.059998,88.970001,43.730000,12.93,47.880001,206.740005,8.23,172.820007,56.325001,NaN,208.270004,113.309998,68.519997,81.309998,93.360001,27.610001,38.000000,38.380001,9.830000,30.059999,114.660004,25.030001,24.969999,67.699997
2022-01-03,32.507626,92.820000,88.610001,43.250000,12.94,48.529999,207.000000,8.71,168.660004,55.700001,NaN,205.289993,111.870003,68.919998,79.349998,91.660004,27.520000,37.889999,37.980000,9.916667,30.139999,112.269997,25.700001,24.379999,67.940002
2022-01-04,33.084686,92.900002,88.650002,43.384998,13.44,49.180000,218.080002,8.92,171.460007,55.639999,NaN,209.500000,112.330002,68.949997,80.339996,90.680000,27.620001,38.119999,37.880001,10.173333,29.990000,116.150002,26.080000,23.920000,68.370003
2022-01-05,33.084686,89.419998,89.470001,42.560001,13.25,47.840000,219.750000,8.81,169.009995,55.770000,NaN,204.229996,112.379997,66.949997,79.029999,89.730003,27.770000,37.500000,37.770000,9.896667,30.049999,109.320000,26.160000,22.840000,69.040001
2022-01-06,32.507626,91.800003,89.180000,42.595001,13.38,48.200001,221.990005,9.08,169.410004,54.825001,NaN,204.309998,113.019997,65.809998,80.379997,85.769997,27.650000,38.270000,37.740002,9.936667,30.010000,109.989998,26.580000,23.400000,68.500000
2022-01-07,32.507626,89.570000,90.800003,41.060001,13.40,49.029999,224.190002,9.24,167.850006,56.064999,NaN,200.039993,113.629997,64.779999,79.269997,86.410004,27.870001,37.369999,37.529999,9.720000,30.250000,106.690002,26.559999,22.549999,69.099998
2022-01-10,31.161158,88.790001,90.500000,40.959999,13.81,48.299999,221.639999,9.12,166.419998,55.849998,NaN,196.320007,112.660004,64.459999,78.410004,84.290001,27.770000,36.660000,37.540001,9.833333,30.230000,107.769997,26.610001,23.540001,69.860001
2022-01-11,31.738214,90.250000,89.769997,41.305000,14.01,48.820000,219.949997,9.33,167.759995,54.369999,NaN,200.330002,110.519997,64.529999,79.559998,84.790001,27.809999,36.970001,37.259998,9.713333,29.950001,109.980003,27.980000,23.969999,68.599998
2022-01-12,31.738214,92.230003,90.290001,41.439999,13.93,48.139999,222.399994,9.63,171.460007,54.619999,NaN,202.399994,110.320000,64.650002,80.029999,85.089996,27.950001,37.459999,37.270000,9.410000,29.959999,110.139999,28.180000,23.910000,68.589996
2022-01-13,32.122921,92.129997,90.860001,40.930000,13.72,48.130001,227.000000,9.44,171.179993,55.320000,NaN,200.110001,110.809998,63.410000,78.430000,84.900002,28.330000,37.509998,37.570000,9.350000,30.000000,107.279999,27.870001,23.770000,69.019997

---
**GARCH Volatility Forecasting**
---
*Code inspired from DataCamp - GARCH Models*

*GARCH(1,1) Model*

---

In [57]:
all_data = [soxx_data, pick_data, mxi_data, futy_data, pave_data, tan_data,
            dtcr_data, volt_data]

combined_data = pd.concat(all_data, axis=1)
combined_data.head()
print(combined_data.columns)

Index(['ADI', 'ALAB', 'AMAT', 'AMD', 'ASML', 'AVGO', 'CRDO', 'ENTG', 'INTC',
       'KLAC',
       ...
       'NEE', 'NI', 'NVT', 'OGE', 'POWL', 'PPL', 'PWR', 'SU', 'VRT', 'XEL'],
      dtype='object', name='Ticker', length=197)

In [58]:
combined_data.shape

(1241, 197)

In [59]:
combined_data.columns.duplicated()
combined_data = combined_data.loc[:, ~combined_data.columns.duplicated()]   #https://stackoverflow.com/questions/14984119/python-pandas-remove-duplicate-columns
print(combined_data.columns.duplicated())
print(combined_data.columns)
combined_data.head(10)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False]
Index(['ADI', 'ALAB', 'AMAT', 'AMD', 'ASML', 'AVGO', 'CRDO', 'ENTG', 'INTC',
       'KLAC',
       ...
       'GEV', 'IDA', 'ITRI', 'JCI', 'NI', 'NVT', 'OGE', 'POWL', 'SU', 'VRT'],
      dtype='object', name='Ticker', length=154)

Ticker,ADI,ALAB,AMAT,AMD,ASML,AVGO,CRDO,ENTG,INTC,KLAC,LRCX,MCHP,MPWR,MRVL,MTSI,MU,NVDA,NVMI,NXPI,ON,QCOM,RMBS,TER,TSM,TXN,1211.SR,AA,AAL,ANTO.L,BHP,BWJ0.F,FCX,FVJA.BE,GLNCY,GMEXICOB.MX,GXD.F,HWHG.BE,IPHB.F,IZ1.BE,MT,NPS.MU,NUE,PKX.BE,RIO,RS,STLD,TECK,VALE,VALT.L,AEE,AEP,ATO,AWK,CEG,CNP,D,DTE,DUK,ED,EIX,ES,ETR,EXC,FE,NEE,NRG,PCG,PEG,PPL,SO,SRE,VST,WEC,XEL,CRH,CSX,DE,EME,EMR,ETN,FAST,FTV,HUBB,HWM,MLM,MTZ,NSC,PH,PWR,ROK,TRMB,TT,UNP,URI,VMC,WWD,6443.TW,66T.BE,AOR.BE,ARRY,CSIQ,CWEN,DORL.TA,DQ,ENLT,ENPH,ENRG.TA,FGSGF,FSLR,GCPEF,GRE.MC,HASI,JKS,NOFR.TA,NXT,RUN,S93.BE,SEDG,SHLS,XNYIF,000660.KS,0788.HK,1686.HK,2344.TW,3006.TW,AJBU.SI,AMT,APLD,ARM,CCI,DLR,EQIX,GDS,SBAC,SMCI,UNIT,VNET,ABJA.MU,AEIS,APH,BELFB,BWXT,CAT,ET,GEV,IDA,ITRI,JCI,NI,NVT,OGE,POWL,SU,VRT
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2021-12-31,175.770004,NaN,157.360001,143.899994,796.140015,66.541000,NaN,138.580002,51.500000,430.109985,71.915001,87.059998,493.329987,87.489998,78.300003,93.150002,29.410999,146.500000,227.779999,67.919998,182.869995,29.389999,163.529999,120.309998,188.470001,NaN,59.580002,17.959999,1338.5,53.835861,NaN,41.730000,NaN,10.08,89.290001,NaN,NaN,NaN,NaN,31.830000,NaN,114.150002,NaN,66.940002,162.220001,62.070000,28.820000,14.02,2306.548096,89.010002,88.970001,104.769997,188.860001,NaN,27.910000,78.559998,119.540001,104.900002,85.320000,68.250000,90.980003,56.325001,41.198288,41.590000,93.360001,43.080002,12.14,66.730003,30.059999,68.580002,66.139999,22.770000,97.070000,67.699997,52.799999,37.599998,342.890015,127.389999,92.970001,172.820007,32.029999,57.490582,208.270004,31.830000,440.519989,92.279999,297.709991,318.119995,114.660004,348.850006,87.190002,202.029999,251.929993,332.290009,207.580002,109.459999,NaN,NaN,NaN,15.69,31.290001,36.029999,NaN,40.320000,NaN,182.940002,NaN,4.43,87.160004,0.297619,NaN,53.119999,45.959999,NaN,NaN,34.299999,NaN,280.570007,24.299999,1.660,NaN,8.6,7.38,NaN,NaN,2.47,292.500000,NaN,NaN,208.740005,176.869995,845.840027,47.160000,389.019989,4.395,23.272425,9.03,NaN,91.059998,43.730000,12.93,47.880001,206.740005,8.23,NaN,113.309998,68.519997,81.309998,27.610001,38.000000,38.380001,9.830000,25.030001,24.969999
2022-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.266666,59.580002,17.959999,1338.5,53.835861,NaN,41.730000,NaN,10.08,89.290001,NaN,NaN,NaN,NaN,31.830000,NaN,114.150002,NaN,66.940002,162.220001,62.070000,28.820000,14.02,2306.548096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-03,177.149994,NaN,159.929993,150.240005,797.489990,66.332001,NaN,138.389999,53.209999,435.089996,72.545998,88.000000,494.850006,89.430000,79.750000,95.750000,30.121000,147.119995,231.220001,70.169998,186.210007,29.320000,166.110001,128.800003,190.600006,26.133333,60.360001,18.750000,1338.5,53.826939,68.190002,41.480000,NaN,10.16,89.089996,7.125,NaN,12.535,NaN,32.119999,2.837,113.040001,NaN,66.730003,161.279999,61.660000,29.110001,13.81,2306.548096,88.580002,88.610001,105.010002,184.139999,NaN,27.620001,78.349998,119.180000,103.489998,85.129997,67.510002,89.129997,55.700001,40.706135,41.240002,91.660004,42.959999,12.21,66.160004,30.139999,68.169998,65.995003,22.740000,96.089996,67.940002,53.200001,37.080002,350.109985,127.360001,91.760002,168.660004,30.990000,55.440845,205.289993,32.330002,439.010010,94.180000,292.350006,316.000000,112.269997,339.660004,86.680000,194.850006,247.770004,330.640015,207.899994,110.480003,41.327625,NaN,NaN,15.91,31.330000,35.959999,1401.0,41.970001,NaN,184.449997,1340.0,4.43,88.580002,0.297619,29.299999,54.060001,46.369999,9640.0,NaN,35.470001,NaN,282.450012,23.840000,1.684,NaN,8.5,7.28,31.822126,164.5,2.47,286.380005,NaN,NaN,207.740005,175.089996,836.109985,45.380001,379.869995,4.562,23.073090,9.01,32.507626,92.820000,43.250000,12.94,48.529999,207.000000,8.71,NaN,111.870003,68.919998,79.349998,27.520000,37.889999,37.980000,9.916667,25.700001,24.379999
2022-01-04,175.550003,NaN,158.360001,144.419998,779.190002,67.092003,NaN,139.220001,53.139999,431.239990,71.199997,87.470001,491.250000,88.370003,78.580002,96.339996,29.290001,144.830002,232.869995,70.949997,187.229996,28.980000,166.380005,133.399994,190.800003,26.333332,57.529999,19.020000,1369.0,54.701160,71.230003,42.150002,NaN,10.45,88.230003,7.005,NaN,12.750,NaN,32.970001,2.883,117.070000,NaN,67.519997,163.570007,63.520000,29.200001,13.55,2306.548096,88.110001,88.650002,106.260002,179.419998,NaN,27.450001,78.099998,119.379997,103.410004,84.970001,66.669998,88.389999,55.639999,40.663338,41.080002,90.680000,42.619999,12.44,65.989998,29.990000,68.169998,67.184998,22.520000,95.849998,68.370003,54.230000,37.630001,371.290009,130.009995,95.830002,171.460007,31.165001,55.666920,209.500000,33.529999,441.510010,96.080002,294.720001,324.040009,116.150002,343.100006,85.110001,195.000000,252.029999,347.089996,210.529999,112.650002,42.310448,NaN,NaN,14.97,31.170000,35.389999,1425.0,42.009998,NaN,178.279999,1350.0,4.43,87.279999,0.297619,28.850000,53.639999,46.189999,9500.0,NaN,34.570000,NaN,273.100006,22.549999,1.660,128500.0,8.8,7.24,31.425591,161.5,2.45,282.769989,NaN,NaN,202.149994,169.089996,814.630005,41.020000,369.459991,4.714,22.325581,8.37,33.084686,92.900002,43.384998,13.44,49.180000,218.080002,8.92,NaN,112.330002,68.949997,80.339996,27.620001,38.119999,37.880001,10.173333,26.080000,23.920000
2022-01-05,172.839996,NaN,153.740005,136.149994,745.669983,64.300003,NaN,132.089996,53.869999,420.739990,69.181000,84.519997,460.529999,84.120003,73.739998,94.400002,27.604000,136.949997,224.570007,67.419998,186.500000,27.910000,160.250000,127.059998,186.820007,26.366667,58.549999,18.680000,1372.0,55.352364,69.930000,41.680000,NaN,10.46,89.540001,7.160,NaN,12.865,NaN,33.029999,2.945,122.720001,NaN,68.709999,166.750000,65.959999,29.420000,13.66,2306.548096,88.330002,89.470001,106.599998,178.100006,NaN,27.389999,79.209999,119.250000,103.639999,85.550003,65.199997,89.230003,55.770000,40.634808,40.799999,89.730003,41.419998,11.86,65.830002,30.049999,68.250000,67.595001,22.110001,96.959999,69.040001,53.349998,37.439999,372.049988,127.099998,95.690002,169.009995,30.770000,54.491333,204.229996,33.320000,437.170013,94.080002,294.709991,318.369995,109.320000,337.359985,81.610001,192.669998,252.789993,335.019989,208.479996,110.389999,41.278484,NaN,NaN,13.92,29.160000,33.970001,1470.0,39.990002,NaN,157.199997,1334.0,4.43,83.510002,0.248016,28.700001,49.860001,43.560001,9607.0,NaN,31.420000,NaN,249.809998,21.320000,1.541,125500.0,8.9,7.03,31.029053,158.0,2.43,264.570007,NaN,NaN,188.460007,162.880005,789.099976,39.070000,350.769989,4.536,21.860464,8.24,33.084686,89.419998,42.560001,13.25,47.840000,219.750000,8.81,NaN,112.379997,66.949997,79.029999,27.770000,37.500000,37.770000,9.896667,26.160000,22.840000
2022-01-06,173.389999,NaN,156.339996,136.229996,763.119995,63.702999,NaN,134.970001,54.009998,432.220001,70.191002,85.300003,465.609985,85.529999,74.680000,95.650002,28.177999,137.000000,226.960007,67.250000,185.949997,28.129999,163.479996,128.470001,186.759995,26.700001,58.450001,18.570000,1328.0,55.414806,70.269997,40.529999,NaN,10.48,90.510002,6.870,NaN,12.695,NaN,33.490002,2.962,116.599998,NaN,70.040001,165.490005,64.050003,29.100000,14.01,2306.548096,87.900002,89.180000,105.769997,175.300003,NaN,27.650000,79.059998,119.570000,103.470001,85.370003,64.620003,88.900002,54.825001,40.463623,40.939999,85.769997,40.639999,11.82,65.889999,30.010000,68.169998,68.080002,22.320000,96.349998,68.500000,52.950001,37.709999,376.359985,127.860001,96.230003,169.410004,30.945000,54.596836,204.309998,33.650002,437.089996,94.480003,296.640015,324.130005,109.989998,335.109985,82.029999,195.029999,253.490005,335.170013,209.949997,110.419998,40.197384,NaN,NaN,13.84,29.170000,34.160000,1410.0,39.869999,NaN,151.490005,1288.0,4.43,83.970001,0.347222,27.049999,49.419998,43.180000,9151.0,NaN,31.480000,NaN,248.240005,21.120001,1.532,125000.0,9.0,7.31,30.384680,155.0,2.39,264.890015,NaN,NaN,192.500000,160.800003,775.080017,41.849998,349.170013,4.510,21.578074,8.37,32.507626,91.800003,42.595001,13.38,48.200001,221.990005,9.08,NaN,113.019997,65.809998,80.379997,27.650000,38.270000,37.740002,9.936667,26.580000,23.400000
2022-01-07,168.839996,NaN,150.809998,132.000000,756.099976,61.915001,NaN,132.009995,53.439999,416.910004,66.929001,81.930000,444.690002,83.110001,72.480003,94.449997,27.247000,131.990005,221.330002,64.559998,180.410004,27.540001,158.270004,123.500000,179.440002,26.700001,62.369999,19.280001,1353.0,57.413025,71.489998,41.880001,NaN,10.75,90.360001,6.875,NaN,12.310,NaN,34.810001,3.049,114.440002,NaN,72.239998,166.529999,62.310001,30.410000,14.81,2306.548096,88.239998,90.800003,105.290001,173.500000,NaN,27.660000,80.209999,119.690002,104.500000,85.669998,65.000000,89.660004,56.064999,40.399429,41.410000,86.410004,40.560001,12.21,67.000000,30.250000,68.639999,69.105003,22.709999,97.209999,69.099998,52.959999,37.509998,378.649994,125.570000,95.690002,167.850006,30.315001,54.220043,200.039993,34.009998,429.200012,93.959999,296.809998,323.739990,106.690002,327.880005,79.139999,189.270004,254.779999,325.980011,207.919998,112.040001,39.558548,NaN,NaN,14.12,29.780001,33.860001,1410.0,40.090000,NaN,145.130005,1288.0,4.43,84.680000,0.277778,27.100000,49.000000,44.650002,9151.0,NaN,31.719999,NaN,248.910004,21.870001,1.532,127000.0,9.2,7.14,30.037708,148.5,2.36,266.579987,NaN,NaN,194.729996,161.059998,774.940002,42.900002,347.910004,4.408,21.661131,8.74,32.507626,89.570000,41.060001,13.40,49.029999,224.190002,9.24,NaN,113.629997,64.779999,79.269997,27.870001,37.369999,37.529999,9.720000,26.559999,22.549999
2022-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.333332,62.369999,19.280001,1353.0,57.413025,71.489998,41.880001,NaN,10.75,90.360001,6.875,NaN,12.310,NaN,34.810001,3.049,114.440002,NaN,72.239998,166.529999,62.310001,30.410000,14.81,2306.548096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-10,170.399994,NaN,149.589996,132.000000,727.169983,62.116001,NaN,133.910004,55.209999,418.730011,66.429001,82.930000,449.329987,82.209999,72.839996,93.889999,27.400000,131.360001,221.830002,65.120003,179.679993,27.389999,156.610001,125.010002,182.960007,28.299999,61.540001,18.790001,1345.5,56.333630,70.419998,41.619999,NaN,10.59,89.250000,6.940,NaN,12.345,NaN,34.299999,3.044,111.860001,NaN,72.709999,162.399994,60.590000,31.200001,14.65,2306.548096,87.510002,90.500000,105.150002,170.029999,NaN,27.690001,79.830002,120.150002,104.559998,84.779999,65.639999,88.989998,55.849998,40.527817,41.520000,84.290001,40.380001,12.23,66.260002,30.230000,68.529999,68.849998,22.459999,96.900002,69.860001,52.259998,36.540001,379.859985,123.839996,95.300003,166.419998,30.084999,54.325546,196.320007,33.980000,416.250000,94.750000,287.970001,317.450012,107.769997,330.149994,78.769997,190.139999,250.279999,322.209991,200.080002,110.550003,40.049957,NaN,NaN,14.01,29.100000,33.150002,1341.0,39.580002,NaN,147.130005,1301.0,4.43,84.300003,0.297619,26.900000,47.889999,44.689999,8800.0,NaN,31.520000,NaN,255.470001,21.530001,1.605,124500.0,9.2,7.19,30.384680,152.0,2.32,264.410004,NaN,NaN,190.669998,159.240005,764.330017,44.740002,342.579987,4.418,21.378738,9.18,31.161158,88.790001,40.959999,13.81,48.299999,221.639999,9.12,NaN,112.660004,64.459999,78.410004,27.770000,36.660000,37.540001,9.833333,26.610001,23.540001
2022-01-11,173.630005,NaN,152.449997,137.309998,729.159973,62.205002,NaN,135.089996,55.910000,425.609985,67.320999,84.610001,452.510010,86.230003,73.610001,94.199997,27.816999,135.110001,227.539993,65.930000,185.399994,27.690001,160.539993,129.169998,184.639999,28.633333,62.200001,19.020000,1342.0,57.528992,69.349998,42.990002,NaN,10.63,89.970001,6.900,NaN,13.205,NaN,35.389999,3.098,110.839996,NaN,74.419998,164.179993,60.970001,32.439999,15.24,2306.548096,86.970001,89.769997,104.639999,168.309998,NaN,27.400000,79.129997,118.779999,103.230003,83.070000,64.360001,86.629997,54.369999,39.671898,41.360001,84.790001,40.880001,12.17,65.849998,29.950001,67.650002,67.919998,22.510000,95.320000,68.599998,53.360001,36.299999,380.549988,124.660004,96.379997,167.759995,30.145000,55.327808,200.330002,33.919998,419.329987,96.570000,286.420013,321.369995,109.980003,335.000000,79.489998,193.479996,246.419998,333.989990,200.440002,113.449997,40.393948,NaN,NaN,14.41,29.510000,33.610001,1360.0,39.599998,NaN,148.509995,1338.0,4.43,84.449997,0.347222,27.500000,48.720001,45.570000,8883.0,NaN,32.730000,NaN,261.089996,22.780001,1.605,128000.0,8.9,7.21,29.740307,145.0,2.30,260.489990,NaN,NaN,187.589996,159.029999,766.880005,46.230000,341.690002,4.491,21.345514,9.19,31.738214,90.250000,41.305000,14.01,48.820000,219.949997,9.33,NaN,110.519997,64.529999,79.559998,27.809999,36.970001,37.259998,9.713333,27.980000,23.969999

In [60]:
fx_map = {
    '.SR': 'SARUSD=X', '.L': 'GBPUSD=X', '.F': 'EURUSD=X',
    '.BE': 'EURUSD=X', '.MX': 'MXNUSD=X', '.MU': 'EURUSD=X',
    '.TW': 'TWDUSD=X', '.TA': 'ILSUSD=X', '.MC': 'EURUSD=X',
    '.KS': 'KRWUSD=X', '.HK': 'HKDUSD=X', '.SI': 'SGDUSD=X'
}

req_fx = list(set(fx_map.values()))
fx_data = yf.download(req_fx, start=start_date, end=end_date)['Close']

port_data_usd = pd.DataFrame(index=combined_data.index)

for ticker in combined_data.columns:
    suffix = next((s for s in fx_map.keys() if ticker.endswith(s)), None)

    if suffix:
        fx_ticker = fx_map[suffix]

        fx_rate = fx_data[fx_ticker].reindex(combined_data.index).ffill()

        if suffix == ['.L', '.TA']:
            port_data_usd[ticker] = (combined_data[ticker] / 100) * fx_rate       #.L Prices often in Pence
        else:                                                                     #1 Israeli New Shekel = 100 Agora -> .TA
            port_data_usd[ticker] = combined_data[ticker] * fx_rate

        print(f"Converted {ticker} ({suffix}) to USD")
    else:
        port_data_usd[ticker] = combined_data[ticker]

/tmp/ipykernel_5187/143804182.py:9: FutureWarning: YF.download() has changed argument auto_adjust default to True
  fx_data = yf.download(req_fx, start=start_date, end=end_date)['Close']
[*********************100%***********************]  9 of 9 completed

Converted 1211.SR (.SR) to USD
Converted ANTO.L (.L) to USD
Converted BWJ0.F (.F) to USD
Converted FVJA.BE (.BE) to USD
Converted GMEXICOB.MX (.MX) to USD
Converted GXD.F (.F) to USD
Converted HWHG.BE (.BE) to USD
Converted IPHB.F (.F) to USD
Converted IZ1.BE (.BE) to USD
Converted NPS.MU (.MU) to USD
Converted PKX.BE (.BE) to USD
Converted VALT.L (.L) to USD
Converted 6443.TW (.TW) to USD
Converted 66T.BE (.BE) to USD
Converted AOR.BE (.BE) to USD
Converted DORL.TA (.TA) to USD
Converted ENRG.TA (.TA) to USD
Converted GRE.MC (.MC) to USD
Converted NOFR.TA (.TA) to USD
Converted S93.BE (.BE) to USD
Converted 000660.KS (.KS) to USD
Converted 0788.HK (.HK) to USD
Converted 1686.HK (.HK) to USD
Converted 2344.TW (.TW) to USD
Converted 3006.TW (.TW) to USD
Converted AJBU.SI (.SI) to USD
Converted ABJA.MU (.MU) to USD

/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker] * fx_rate
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]
/tmp/ipykernel_5187/143804182.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  port_data_usd[ticker] = combined_data[ticker]

In [61]:
port_data_usd.to_csv('port_data_usd.csv')

In [62]:
print(combined_data.describe())

Ticker          ADI        ALAB         AMAT          AMD         ASML  \
count   1003.000000  447.000000  1003.000000  1003.000000  1003.000000
mean     195.624277  101.591141   156.464128   125.977178   727.203160
std       31.750787   50.100207    43.717480    41.818968   160.800160
min      136.729996   36.369999    74.410004    55.939999   379.130005
25%      169.230003   64.560001   118.595001    96.189999   624.190002
50%      190.949997   88.430000   151.539993   116.610001   700.239990
75%      223.625000  135.084999   188.325005   155.800003   808.039978
max      283.390015  251.880005   275.149994   264.329987  1140.920044

Ticker         AVGO        CRDO         ENTG         INTC         KLAC  \
count   1003.000000  985.000000  1003.000000  1003.000000  1003.000000
mean     139.637746   39.871843   100.912951    32.449252   602.728335
std       93.360844   42.698562    19.731972     9.085460   240.222969
min       42.709999    7.350000    62.709999    18.129999   263.220001
25%       59.901501   14.180000    85.100002    24.395000   384.379990
50%      110.767998   18.850000   100.599998    31.230000   566.809998
75%      181.104996   45.869999   112.484997    38.170000   757.024994
max      412.970001  189.190002   146.479996    55.910000  1279.599976

Ticker         LRCX         MCHP         MPWR         MRVL         MTSI  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      74.891036    73.099472   603.759422    65.231426    91.656072
std       28.780353    12.021621   183.615502    18.331031    32.578479
min       31.495001    35.340000   309.200012    34.680000    44.080002
25%       51.576000    64.935001   454.590012    52.344999    63.004999
50%       71.592003    74.139999   570.349976    64.510002    84.860001
75%       89.126999    82.070000   731.584991    73.549999   115.615002
max      178.070007    99.489998  1105.050049   126.059998   189.860001

Ticker           MU         NVDA         NVMI         NXPI           ON  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      93.792054    79.056491   163.772253   204.856351    66.805404
std       43.079825    58.309652    71.902094    31.338037    14.585408
min       48.880001    11.227000    69.500000   138.089996    31.950001
25%       64.665001    23.919000   100.965000   179.525002    55.080002
50%       83.389999    49.604000   135.389999   205.479996    67.629997
75%      107.634998   129.884995   210.745003   226.775002    75.610001
max      294.369995   207.039993   351.579987   290.779999   108.089996

Ticker         QCOM         RMBS          TER          TSM          TXN  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean     147.633181    52.240698   110.548923   143.517627   177.344407
std       25.252279    19.728759    24.601205    63.871637    15.929601
min      103.019997    20.590000    67.959999    60.279999   140.500000
25%      124.364998    37.930000    93.855000    90.919998   165.869995
50%      150.720001    54.240002   106.019997   122.309998   175.899994
75%      166.529999    62.020000   119.594997   186.904999   187.040001
max      227.089996   113.610001   204.009995   310.140015   221.250000

Ticker      1211.SR           AA          AAL       ANTO.L          BHP  \
count   1236.000000  1237.000000  1237.000000  1237.000000  1237.000000
mean      46.336192    40.554559    13.987268  1714.530302    56.926047
std        7.275267    13.557569     2.298670   417.865048     5.402203
min       26.133333    22.570000     9.070000   991.599976    40.220001
25%       41.987500    31.330000    12.260000  1437.500000    53.040001
50%       46.000000    36.820000    13.950000  1666.000000    57.119999
75%       50.549999    45.650002    15.510000  1868.500000    60.480000
max       67.900002    95.059998    20.219999  3316.000000    71.239998

Ticker       BWJ0.F          FCX  FVJA.BE        GLNCY  GMEXICOB.MX  \
count   1235.000000  1237.000000      0.0  1237.000000  1237.000000
mean      62.070316    40.579070      NaN    10.603897    98.278618
std       11.105428     5.721405      NaN     1.667621    21.387752
min       45.599998    25.090000      NaN     5.840000    62.020000
25%       53.500000    37.419998      NaN     9.530000    82.730003
50%       59.500000    40.259998      NaN    10.860000    96.900002
75%       69.500000    44.119999      NaN    11.670000   105.860001
max       95.500000    54.860001      NaN    14.310000   174.600006

Ticker        GXD.F  HWHG.BE       IPHB.F  IZ1.BE           MT       NPS.MU  \
count   1235.000000      0.0  1235.000000     0.0  1237.000000  1235.000000
mean       8.208392      NaN     7.757874     NaN    28.072377     3.660558
std        2.400636      NaN     3.288099     NaN     4.936265     0.484642
min        4.738000      NaN     2.790000     NaN    19.850000     2.589200
25%        6.651000      NaN     4.790000     NaN    24.620001     3.234000
50%        7.800000      NaN     7.440000     NaN    27.010000     3.727200
75%        9.207500      NaN    10.600000     NaN    30.590000     4.045000
max       18.100000      NaN    17.299999     NaN    46.250000     4.708000

Ticker          NUE  PKX.BE          RIO           RS         STLD  \
count   1237.000000     0.0  1237.000000  1237.000000  1237.000000
mean     145.902951     NaN    65.856637   257.253597   113.125602
std       21.246426     NaN     6.213290    47.511668    24.982867
min       93.040001     NaN    51.220001   149.059998    52.450001
25%      132.050003     NaN    61.580002   210.559998    98.949997
50%      146.190002     NaN    64.800003   275.320007   116.540001
75%      160.770004     NaN    69.820000   290.140015   130.339996
max      200.970001     NaN    84.000000   343.660004   177.199997

Ticker         TECK         VALE       VALT.L          AEE          AEP  \
count   1237.000000  1237.000000  1237.000000  1003.000000  1003.000000
mean      40.258852    13.080946  2600.408075    87.105623    94.723818
std        5.550803     2.771191   799.639532     9.580033    11.029396
min       25.730000     8.260000  2306.548096    67.919998    71.330002
25%       36.450001    10.630000  2306.548096    80.305000    86.570000
50%       40.570000    13.070000  2306.548096    87.459999    94.349998
75%       43.490002    14.930000  2306.548096    95.195000   102.045002
max       54.770000    21.230000  6520.000000   106.349998   123.769997

Ticker          ATO          AWK         CEG          CNP            D  \
count   1003.000000  1003.000000  991.000000  1003.000000  1003.000000
mean     127.753888   140.269551  168.357278    31.139352    59.566640
std       20.639572    11.910988   99.916563     3.757631    11.698400
min       98.110001   113.820000   41.897999    25.549999    39.529999
25%      113.719997   131.504997   83.849998    28.315000    52.245001
50%      117.190002   141.100006  121.269997    29.980000    56.630001
75%      143.074997   147.870003  242.095001    32.429998    61.585001
max      179.190002   188.860001  403.950012    40.220001    88.379997

Ticker          DTE          DUK           ED          EIX           ES  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean     120.460907   105.530608    95.132782    66.408245    70.065773
std       11.678605    10.931554     6.189304     8.864639    11.211364
min       94.199997    85.440002    79.470001    48.320000    52.459999
25%      110.864998    95.950001    90.330002    59.055000    60.805000
50%      119.599998   105.050003    95.070000    66.989998    66.449997
75%      130.884995   115.174999    99.360001    70.834999    79.575001
max      143.320007   129.029999   113.300003    88.360001    93.959999

Ticker          ETR          EXC           FE          NEE          NRG  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      63.231565    41.269218    40.411486    73.941216    73.176391
std       15.087886     3.571357     2.911301     8.468333    44.077243
min       44.435001    33.619999    32.599998    49.320000    30.820000
25%       51.987499    38.424999    38.270000    70.070000    38.260000
50%       55.924999    41.209999    40.099998    74.379997    50.939999
75%       76.424999    43.700001    42.325001    80.049999    94.920002
max       97.650002    50.250000    48.459999    93.360001   178.500000

Ticker          PCG          PEG          PPL           SO          SRE  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      15.878554    70.820409    29.947238    77.527029    77.730823
std        2.501353    10.393443     3.701326     9.868654     6.600743
min        9.780000    53.480000    22.549999    61.500000    63.779999
25%       14.740000    61.674999    26.940000    69.074997    72.439999
50%       16.290001    67.099998    29.020000    74.089996    76.750000
75%       17.299999    81.115002    33.245001    87.774998    82.170002
max       21.629999    94.510002    37.970001    99.720001    94.769997

Ticker          VST          WEC          XEL          CRH          CSX  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      77.662253    94.986002    66.366979    70.342134    32.850229
std       63.319372     9.966948     7.008009    26.395160     2.482091
min       20.809999    76.459999    48.439999    31.540001    26.510000
25%       24.350000    86.665001    61.119999    47.325001    31.120000
50%       38.380001    94.930000    67.599998    68.269997    32.990002
75%      131.215004   103.790001    70.915001    92.735001    34.580002
max      217.919998   117.500000    82.110001   128.940002    38.380001

Ticker           DE          EME          EMR          ETN         FAST  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean     410.921366   302.721685   103.810828   247.585623    32.849835
std       49.476126   175.859928    17.817907    83.526196     6.902051
min      289.140015    96.260002    73.059998   125.040001    21.934999
25%      375.794998   148.479996    89.570000   162.180000    26.985001
50%      401.269989   220.779999    97.949997   238.639999    31.635000
75%      442.759995   434.925003   115.994999   327.050003    38.119999
max      531.479980   777.000000   149.630005   392.760010    50.389999

Ticker          FTV         HUBB          HWM          MLM          MTZ  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      52.690325   323.430598    82.700289   471.192353   110.843938
std        5.241398    89.807852    54.384817   101.810546    40.934855
min       40.361717   171.330002    30.639999   296.049988    47.599998
25%       48.944988   236.339996    39.145000   366.809998    82.430000
50%       52.434063   328.100006    53.730000   477.029999    96.559998
75%       56.318764   402.789993   116.040001   558.980011   127.920002
max       65.026375   472.570007   212.169998   656.849976   232.940002

Ticker          NSC           PH          PWR          ROK         TRMB  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean     243.074157   483.221377   233.753819   284.415105    62.382752
std       25.483642   177.616069    97.189043    40.765447    10.805180
min      184.529999   236.369995    96.889999   191.089996    40.820000
25%      224.135002   313.715012   148.354996   262.020004    53.475000
50%      243.240005   458.190002   205.570007   278.529999    60.240002
75%      257.529999   635.715027   300.805008   303.089996    71.219997
max      300.410004   899.130005   466.910004   413.049988    87.190002

Ticker           TT          UNP          URI          VMC          WWD  \
count   1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean     270.501505   226.336481   557.597697   224.708415   152.053121
std      105.245657    17.488002   209.561899    44.773763    54.652152
min      120.970001   185.720001   235.839996   141.449997    80.260002
25%      175.190002   212.565002   355.050003   181.519997   107.690002
50%      243.130005   227.300003   559.179993   224.350006   135.869995
75%      375.059998   240.625000   719.925018   264.539993   181.074997
max      472.540009   276.690002  1020.000000   309.070007   316.170013

Ticker      6443.TW  66T.BE  AOR.BE         ARRY         CSIQ         CWEN  \
count   1042.000000     0.0     0.0  1043.000000  1043.000000  1043.000000
mean      27.895369     NaN     NaN    13.014669    24.054813    29.653605
std        8.462452     NaN     NaN     5.871705    10.742180     4.314117
min       11.950000     NaN     NaN     3.980000     6.760000    18.760000
25%       19.662500     NaN     NaN     7.470000    13.570000    26.400000
50%       28.700001     NaN     NaN    12.010000    22.969999    29.770000
75%       34.791866     NaN     NaN    18.469999    33.905001    32.719999
max       47.765106     NaN     NaN    26.320000    47.009998    41.610001

Ticker      DORL.TA           DQ        ENLT         ENPH      ENRG.TA  \
count   1042.000000  1043.000000  781.000000  1043.000000  1042.000000
mean    1192.458926    32.556232   18.905268   134.238150  1254.554319
std      457.808237    14.698295    7.070020    78.090813   145.391950
min      530.200012    12.740000    1.960000    26.120001   947.000000
25%      831.100006    19.840000   16.180000    66.435001  1155.000000
50%     1152.000000    28.190001   17.030001   120.110001  1259.500000
75%     1387.750000    43.100000   18.750000   183.845001  1340.000000
max     3633.000000    77.000000   45.750000   336.000000  1802.000000

Ticker        FGSGF         FSLR        GCPEF       GRE.MC         HASI  \
count   1043.000000  1043.000000  1043.000000  1042.000000  1043.000000
mean       2.345072   166.996827     0.197839    37.065048    30.379310
std        0.978219    52.717908     0.084539    14.760073     6.479113
min        1.070000    61.400002     0.029762    18.530001    14.360000
25%        1.500000   136.774994     0.140000    27.755000    25.950000
50%        1.700000   168.539993     0.170000    32.520000    28.760000
75%        3.450000   201.650002     0.250000    37.637501    33.360001
max        4.430000   300.709991     0.486111    86.300003    54.060001

Ticker          JKS       NOFR.TA         NXT          RUN  S93.BE  \
count   1043.000000   1042.000000  754.000000  1043.000000     0.0
mean      35.244727   9033.064299   48.909715    17.885681     NaN
std       14.150169    807.929173   16.206078     7.383758     NaN
min       13.880000   7020.000000   28.549999     5.665000     NaN
25%       23.330000   8499.000000   38.385000    11.670000     NaN
50%       29.299999   8809.500000   42.994999    17.320000     NaN
75%       47.525000   9449.000000   56.697500    22.964999     NaN
max       75.540001  11320.000000  111.839996    38.650002     NaN

Ticker         SEDG         SHLS        XNYIF      000660.KS      0788.HK  \
count   1043.000000  1043.000000  1043.000000    1038.000000  1040.000000
mean     140.232641    13.779070     0.832378  173707.899807     9.711231
std      120.921560     7.822494     0.458419  109001.904716     1.310993
min       10.465000     2.810000     0.271600   75000.000000     7.100000
25%       26.139999     6.065000     0.430000  107500.000000     8.800000
50%       76.989998    13.550000     0.676400  136000.000000     9.600000
75%      275.455002    21.050000     1.140050  196000.000000    10.900000
max      365.410004    31.160000     1.890000  651000.000000    12.780000

Ticker      1686.HK      2344.TW      3006.TW      AJBU.SI          AMT  \
count   1040.000000  1039.000000  1039.000000  1040.000000  1040.000000
mean       4.782288    25.615160    83.822185     2.055322   209.822538
std        1.648783     9.773355    24.866237     0.202190    25.753763
min        2.380000    13.350000    43.750000     1.600000   157.679993
25%        3.392500    20.112137    68.099998     1.900000   191.027500
50%        4.390000    24.833155    80.000000     2.080000   207.110001
75%        6.272500    27.554674    91.750000     2.200000   223.389999
max        9.640000    83.699997   178.000000     2.470000   292.500000

Ticker        APLD         ARM          CCI          DLR         EQIX  \
count   967.000000  596.000000  1040.000000  1040.000000  1040.000000
mean      7.295328  124.007701   121.322798   140.150856   769.734606
std       6.870303   33.614575    30.608953    25.489019    89.043966
min       0.880000   47.869999    84.330002    86.489998   505.390015
25%       3.110000  111.535002    99.239998   121.297497   709.895004
50%       5.240000  132.880005   109.430000   141.509995   768.399994
75%       8.280000  145.945004   136.727501   159.735001   819.757507
max      37.759998  186.460007   208.740005   195.690002   985.000000

Ticker          GDS         SBAC         SMCI         UNIT         VNET  \
count   1040.000000  1040.000000  1040.000000  1040.000000  1040.000000
mean      21.588620   246.491125    32.766510    10.124279     5.039298
std       10.925195    47.816944    26.162794     4.552810     2.608800
min        5.060000   186.119995     3.483000     4.401993     1.420000
25%       11.230000   212.837498     8.331000     7.148214     2.930000
50%       20.655000   229.979996    29.470000     8.970100     4.860000
75%       29.555000   281.872490    45.327499    10.436047     6.432500
max       48.500000   389.019989   118.806999    23.372093    14.680000

Ticker      ABJA.MU         AEIS          APH        BELFB         BWXT  \
count   1032.000000  1033.000000  1033.000000  1033.000000  1033.000000
mean      41.237775   108.360242    59.860499    61.675353    91.575973
std       11.562150    30.678398    28.002379    37.615498    39.669932
min       23.851749    69.330002    31.254999    11.850000    42.779999
25%       30.600000    89.839996    38.945000    34.040001    59.349998
50%       39.000000   100.870003    48.290001    58.320000    78.830002
75%       51.599998   113.930000    69.300003    77.320000   109.239998
max       64.400002   225.800003   143.850006   177.229996   215.860001

Ticker          CAT           ET         GEV          IDA         ITRI  \
count   1033.000000  1033.000000  455.000000  1033.000000  1033.000000
mean     305.448373    14.470087  376.398769   107.173311    81.640929
std       97.504645     2.814436  172.416913    10.611982    27.453322
min      162.440002     8.230000  122.699997    86.940002    41.790001
25%      224.539993    12.300000  199.035004    98.620003    54.570000
50%      287.570007    13.900000  338.940002   106.339996    74.040001
75%      359.880005    16.629999  558.100006   113.410004   105.820000
max      625.609985    21.080000  723.000000   137.699997   138.419998

Ticker          JCI           NI          NVT          OGE         POWL  \
count   1033.000000  1033.000000  1033.000000  1033.000000  1033.000000
mean      71.958606    31.689226    58.355673    39.147164    42.692323
std       18.782562     5.767143    20.559766     3.880960    33.156701
min       46.299999    23.180000    29.959999    31.940001     6.303333
25%       58.299999    27.219999    39.150002    35.680000    12.133333
50%       66.239998    28.930000    55.439999    38.959999    28.683332
75%       80.040001    36.910000    72.870003    42.570000    63.663334
max      122.660004    44.169998   114.349998    47.040001   136.123337

Ticker           SU          VRT
count   1033.000000  1033.000000
mean      35.246757    64.309342
std        4.178540    51.053082
min       25.030001     8.220000
25%       31.940001    14.520000
50%       34.849998    48.779999
75%       38.770000   105.199997
max       45.200001   199.270004

In [63]:
print(combined_data.count().sort_values())

Ticker
PKX.BE            0
IZ1.BE            0
HWHG.BE           0
FVJA.BE           0
S93.BE            0
66T.BE            0
AOR.BE            0
ALAB            447
GEV             455
ARM             596
NXT             754
ENLT            781
APLD            967
CRDO            985
CEG             991
KLAC           1003
NVDA           1003
NVMI           1003
NXPI           1003
ON             1003
QCOM           1003
RMBS           1003
TER            1003
TSM            1003
TXN            1003
DUK            1003
LRCX           1003
ADI            1003
AMD            1003
ASML           1003
INTC           1003
AMAT           1003
EXC            1003
ETR            1003
FE             1003
CNP            1003
AEP            1003
ATO            1003
AEE            1003
ED             1003
DTE            1003
D              1003
AWK            1003
ES             1003
HWM            1003
HUBB           1003
FTV            1003
FAST           1003
VST            1003
SRE            1003
SO             1003
PPL            1003
PEG            1003
PCG            1003
XEL            1003
WEC            1003
NRG            1003
NEE            1003
EIX            1003
MCHP           1003
MPWR           1003
MRVL           1003
AVGO           1003
ENTG           1003
WWD            1003
VMC            1003
URI            1003
UNP            1003
TT             1003
TRMB           1003
NSC            1003
PH             1003
PWR            1003
ROK            1003
CRH            1003
CSX            1003
DE             1003
EME            1003
EMR            1003
ETN            1003
MLM            1003
MTZ            1003
MTSI           1003
MU             1003
ABJA.MU        1032
NI             1033
ITRI           1033
JCI            1033
ET             1033
AEIS           1033
APH            1033
BELFB          1033
BWXT           1033
NVT            1033
OGE            1033
POWL           1033
CAT            1033
IDA            1033
VRT            1033
SU             1033
000660.KS      1038
2344.TW        1039
3006.TW        1039
0788.HK        1040
UNIT           1040
SMCI           1040
SBAC           1040
GDS            1040
EQIX           1040
DLR            1040
CCI            1040
VNET           1040
AMT            1040
AJBU.SI        1040
1686.HK        1040
DORL.TA        1042
NOFR.TA        1042
GRE.MC         1042
ENRG.TA        1042
6443.TW        1042
ARRY           1043
GCPEF          1043
FSLR           1043
XNYIF          1043
ENPH           1043
CSIQ           1043
HASI           1043
FGSGF          1043
DQ             1043
CWEN           1043
SHLS           1043
JKS            1043
RUN            1043
SEDG           1043
BWJ0.F         1235
IPHB.F         1235
GXD.F          1235
NPS.MU         1235
1211.SR        1236
STLD           1237
GMEXICOB.MX    1237
NUE            1237
VALT.L         1237
RS             1237
GLNCY          1237
FCX            1237
ANTO.L         1237
AAL            1237
AA             1237
BHP            1237
VALE           1237
MT             1237
RIO            1237
TECK           1237
dtype: int64

In [64]:
print(combined_data.std().sort_values())

Ticker
GCPEF               0.084539
AJBU.SI             0.202190
XNYIF               0.458419
NPS.MU              0.484642
FGSGF               0.978219
0788.HK             1.310993
1686.HK             1.648783
GLNCY               1.667621
AAL                 2.298670
GXD.F               2.400636
CSX                 2.482091
PCG                 2.501353
VNET                2.608800
VALE                2.771191
ET                  2.814436
FE                  2.911301
IPHB.F              3.288099
EXC                 3.571357
PPL                 3.701326
CNP                 3.757631
OGE                 3.880960
SU                  4.178540
CWEN                4.314117
UNIT                4.552810
MT                  4.936265
FTV                 5.241398
BHP                 5.402203
TECK                5.550803
FCX                 5.721405
NI                  5.767143
ARRY                5.871705
ED                  6.189304
RIO                 6.213290
HASI                6.479113
SRE                 6.600743
APLD                6.870303
FAST                6.902051
XEL                 7.008009
ENLT                7.070020
1211.SR             7.275267
RUN                 7.383758
SHLS                7.822494
6443.TW             8.462452
NEE                 8.468333
EIX                 8.864639
INTC                9.085460
AEE                 9.580033
2344.TW             9.773355
SO                  9.868654
WEC                 9.966948
PEG                10.393443
IDA                10.611982
CSIQ               10.742180
TRMB               10.805180
GDS                10.925195
DUK                10.931554
AEP                11.029396
BWJ0.F             11.105428
ES                 11.211364
ABJA.MU            11.562150
DTE                11.678605
D                  11.698400
AWK                11.910988
MCHP               12.021621
AA                 13.557569
JKS                14.150169
ON                 14.585408
DQ                 14.698295
GRE.MC             14.760073
ETR                15.087886
TXN                15.929601
NXT                16.206078
UNP                17.488002
EMR                17.817907
MRVL               18.331031
JCI                18.782562
RMBS               19.728759
ENTG               19.731972
NVT                20.559766
ATO                20.639572
NUE                21.246426
GMEXICOB.MX        21.387752
TER                24.601205
3006.TW            24.866237
STLD               24.982867
QCOM               25.252279
NSC                25.483642
DLR                25.489019
AMT                25.753763
SMCI               26.162794
CRH                26.395160
ITRI               27.453322
APH                28.002379
LRCX               28.780353
CCI                30.608953
AEIS               30.678398
NXPI               31.338037
ADI                31.750787
MTSI               32.578479
POWL               33.156701
ARM                33.614575
BELFB              37.615498
BWXT               39.669932
ROK                40.765447
MTZ                40.934855
AMD                41.818968
CRDO               42.698562
MU                 43.079825
AMAT               43.717480
NRG                44.077243
VMC                44.773763
RS                 47.511668
SBAC               47.816944
DE                 49.476126
ALAB               50.100207
VRT                51.053082
FSLR               52.717908
HWM                54.384817
WWD                54.652152
NVDA               58.309652
VST                63.319372
TSM                63.871637
NVMI               71.902094
ENPH               78.090813
ETN                83.526196
EQIX               89.043966
HUBB               89.807852
AVGO               93.360844
PWR                97.189043
CAT                97.504645
CEG                99.916563
MLM               101.810546
TT                105.245657
SEDG              120.921560
ENRG.TA           145.391950
ASML              160.800160
GEV               172.416913
EME               175.859928
PH                177.616069
MPWR              183.615502
URI               209.561899
KLAC              240.222969
ANTO.L            417.865048
DORL.TA           457.808237
VALT.L            799.639532
NOFR.TA           807.929173
000660.KS      109001.904716
FVJA.BE                  NaN
HWHG.BE                  NaN
IZ1.BE                   NaN
PKX.BE                   NaN
66T.BE                   NaN
AOR.BE                   NaN
S93.BE                   NaN
dtype: float64

In [65]:
print(combined_data.isna().sum().sort_values())

Ticker
FCX               4
AA                4
BHP               4
AAL               4
ANTO.L            4
MT                4
VALT.L            4
VALE              4
NUE               4
RIO               4
STLD              4
RS                4
TECK              4
GLNCY             4
GMEXICOB.MX       4
1211.SR           5
GXD.F             6
NPS.MU            6
BWJ0.F            6
IPHB.F            6
FSLR            198
GCPEF           198
CWEN            198
CSIQ            198
HASI            198
SHLS            198
RUN             198
XNYIF           198
SEDG            198
JKS             198
FGSGF           198
ENPH            198
ARRY            198
DQ              198
DORL.TA         199
ENRG.TA         199
GRE.MC          199
6443.TW         199
NOFR.TA         199
1686.HK         201
0788.HK         201
AMT             201
AJBU.SI         201
SMCI            201
GDS             201
EQIX            201
DLR             201
CCI             201
VNET            201
UNIT            201
SBAC            201
3006.TW         202
2344.TW         202
000660.KS       203
AEIS            208
CAT             208
IDA             208
ITRI            208
BWXT            208
ET              208
BELFB           208
APH             208
NVT             208
VRT             208
NI              208
POWL            208
SU              208
OGE             208
JCI             208
ABJA.MU         209
ROK             238
FE              238
WWD             238
VMC             238
URI             238
UNP             238
TT              238
TRMB            238
ETR             238
EXC             238
AEP             238
AEE             238
ATO             238
MTSI            238
MCHP            238
LRCX            238
MRVL            238
NVDA            238
ON              238
NXPI            238
NEE             238
NRG             238
PPL             238
SO              238
PCG             238
PEG             238
ETN             238
EMR             238
EME             238
DE              238
CSX             238
CRH             238
XEL             238
PWR             238
DTE             238
D               238
CNP             238
AWK             238
EIX             238
ED              238
QCOM            238
RMBS            238
ES              238
DUK             238
TXN             238
NVMI            238
TSM             238
TER             238
MU              238
ADI             238
MPWR            238
AMAT            238
AMD             238
ASML            238
ENTG            238
AVGO            238
KLAC            238
INTC            238
FAST            238
FTV             238
HUBB            238
HWM             238
MLM             238
MTZ             238
NSC             238
PH              238
SRE             238
WEC             238
VST             238
CEG             250
CRDO            256
APLD            274
ENLT            460
NXT             487
ARM             645
GEV             786
ALAB            794
66T.BE         1241
PKX.BE         1241
FVJA.BE        1241
HWHG.BE        1241
IZ1.BE         1241
S93.BE         1241
AOR.BE         1241
dtype: int64

In [66]:
import numpy as np

#soxx_ret = (soxx_data.pct_change()) * 100     #Test
#soxx_vol = np.sqrt(252) * soxx_ret.std()
#soxx_vol.head(50)

combined_ret = (combined_data.pct_change()) * 100

combined_vol = np.sqrt(252) * combined_ret.std()    #annualised volatility

combined_vol.head(20)

/tmp/ipykernel_5187/3603273693.py:7: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  combined_ret = (combined_data.pct_change()) * 100

Ticker
ADI     30.426941
ALAB    81.801435
AMAT    39.186719
AMD     49.098908
ASML    38.257809
AVGO    40.623952
CRDO    71.710195
ENTG    47.236568
INTC    44.319942
KLAC    38.352162
LRCX    41.395979
MCHP    40.692688
MPWR    50.119544
MRVL    54.920113
MTSI    38.741334
MU      45.378976
NVDA    48.473478
NVMI    42.572034
NXPI    36.280008
ON      48.228864
dtype: float64

In [67]:
!pip install arch
from arch import arch_model

garch_results = {}

for col in combined_ret.columns:
    series = combined_ret[col].dropna()

    if series.empty:
        print(f"Skipping {col} because it is empty.")
        continue

    model = arch_model(
        series,           #arch_model requires 1D input
        p=1,              #p is the number of lagged/delayed volatility terms. Represents how long it takes shock-induced volatility to decay (1=yesterday's forecast)
        q=1,              #q is the number of lagged residuals/errors. Represents how impactful the news is on volatility (1=yesterday's news)
        mean='constant',  #Mean does not change over time (Assumption)
        vol='GARCH',      #GARCH opposed to ARCH (G=Generalised) adds the p term, and therefore generalises volatility forecast over time
        dist='normal'     #Assume returns are normally distributed
    )                     #GARCH(p=2, q=2) or over often overfits

    res = model.fit(disp="off")
    garch_results[col] = res
    forecast = res.forecast(horizon=5)
    print(col)
    print(forecast.variance.iloc[-1])
    print("-" * 40)

Requirement already satisfied: arch in /usr/local/lib/python3.12/dist-packages (8.0.0)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from arch) (2.0.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from arch) (2.2.2)
Requirement already satisfied: scipy>=1.8 in /usr/local/lib/python3.12/dist-packages (from arch) (1.16.3)
Requirement already satisfied: statsmodels>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from arch) (0.14.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from arch) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->arch) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->arch) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->arch) (2026.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->arch) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->arch) (1.17.0)
ADI
h.1    2.250140
h.2    2.334334
h.3    2.413344
h.4    2.487489
h.5    2.557069
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ALAB
h.1    25.872601
h.2    25.872601
h.3    25.872601
h.4    25.872601
h.5    25.872601
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AMAT
h.1    4.904776
h.2    4.937363
h.3    4.968927
h.4    4.999502
h.5    5.029119
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AMD
h.1    8.018875
h.2    8.267357
h.3    8.474340
h.4    8.646757
h.5    8.790379
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ASML
h.1    4.417721
h.2    4.433620
h.3    4.449328
h.4    4.464848
h.5    4.480181
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AVGO
h.1    4.275333
h.2    4.763770
h.3    5.159956
h.4    5.481316
h.5    5.741981
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
CRDO
h.1    20.814109
h.2    20.812893
h.3    20.811693
h.4    20.810509
h.5    20.809340
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ENTG
h.1    6.922570
h.2    6.991432
h.3    7.057840
h.4    7.121881
h.5    7.183641
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
INTC
h.1    5.912278
h.2    6.687430
h.3    7.233384
h.4    7.617911
h.5    7.888741
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
KLAC
h.1    4.549874
h.2    4.575998
h.3    4.601514
h.4    4.626436
h.5    4.650778
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
LRCX
h.1    6.231523
h.2    6.242439
h.3    6.253088
h.4    6.263476
h.5    6.273611
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
MCHP
h.1    4.307170
h.2    4.376199
h.3    4.443015
h.4    4.507687
h.5    4.570286
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
MPWR
h.1    5.964814
h.2    6.220502
h.3    6.460580
h.4    6.686001
h.5    6.897661
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
MRVL
h.1     8.837972
h.2     9.877770
h.3    10.636296
h.4    11.189635
h.5    11.593293
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
MTSI
h.1    4.507071
h.2    4.610153
h.3    4.706377
h.4    4.796201
h.5    4.880050
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
MU
h.1    11.957892
h.2    11.912488
h.3    11.867794
h.4    11.823799
h.5    11.780492
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NVDA
h.1    6.034580
h.2    6.159782
h.3    6.280707
h.4    6.397503
h.5    6.510309
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NVMI
h.1    6.789692
h.2    6.790147
h.3    6.790600
h.4    6.791050
h.5    6.791498
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NXPI
h.1    3.075737
h.2    3.157435
h.3    3.235962
h.4    3.311441
h.5    3.383991
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ON
h.1    6.319307
h.2    6.594425
h.3    6.844184
h.4    7.070921
h.5    7.276758
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
QCOM
h.1    2.845174
h.2    2.927548
h.3    3.006592
h.4    3.082438
h.5    3.155218
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
RMBS
h.1    7.728858
h.2    7.826756
h.3    7.918036
h.4    8.003143
h.5    8.082497
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
TER
h.1    9.363311
h.2    9.351124
h.3    9.338995
h.4    9.326923
h.5    9.314909
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
TSM
h.1    3.879547
h.2    3.916277
h.3    3.951180
h.4    3.984347
h.5    4.015864
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
TXN
h.1    2.246793
h.2    2.304496
h.3    2.358150
h.4    2.408037
h.5    2.454423
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
1211.SR
h.1    5.320142
h.2    5.882489
h.3    6.444836
h.4    7.007183
h.5    7.569530
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AA
h.1    8.287469
h.2    8.353906
h.3    8.417426
h.4    8.478158
h.5    8.536224
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AAL
h.1    6.176983
h.2    6.190112
h.3    6.203094
h.4    6.215932
h.5    6.228626
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ANTO.L
h.1    3.984261
h.2    3.984224
h.3    3.984187
h.4    3.984151
h.5    3.984115
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
BHP
h.1    2.226293
h.2    2.253826
h.3    2.280440
h.4    2.306165
h.5    2.331030
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
BWJ0.F
h.1    3.870880
h.2    3.976620
h.3    4.069445
h.4    4.150932
h.5    4.222467
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
FCX
h.1    4.665255
h.2    4.718772
h.3    4.770262
h.4    4.819800
h.5    4.867462
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
Skipping FVJA.BE because it is empty.
GLNCY
h.1    2.986011
h.2    3.029130
h.3    3.070820
h.4    3.111126
h.5    3.150096
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
GMEXICOB.MX
h.1    3.692585
h.2    3.728979
h.3    3.763911
h.4    3.797438
h.5    3.829616
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
GXD.F
h.1    5.710160
h.2    5.792459
h.3    5.869311
h.4    5.941078
h.5    6.008096
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
Skipping HWHG.BE because it is empty.
IPHB.F
h.1    14.527393
h.2    12.727479
h.3    12.579481
h.4    12.567312
h.5    12.566312
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
Skipping IZ1.BE because it is empty.
MT
h.1    2.634593
h.2    2.673198
h.3    2.710979
h.4    2.747956
h.5    2.784146
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NPS.MU
h.1    2.430396
h.2    2.623255
h.3    2.649251
h.4    2.652755
h.5    2.653227
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NUE
h.1    3.242130
h.2    3.246037
h.3    3.249918
h.4    3.253776
h.5    3.257608
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
Skipping PKX.BE because it is empty.
RIO
h.1    1.825754
h.2    1.846410
h.3    1.866498
h.4    1.886034
h.5    1.905032
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
RS
h.1    2.034457
h.2    2.139513
h.3    2.227983
h.4    2.302484
h.5    2.365222
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
STLD
h.1    3.293420
h.2    3.296995
h.3    3.300551
h.4    3.304089
h.5    3.307608
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
TECK
h.1    4.864877
h.2    4.914463
h.3    4.962602
h.4    5.009336
h.5    5.054707
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
VALE
h.1    2.714819
h.2    2.722831
h.3    2.730775
h.4    2.738652
h.5    2.746461
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
VALT.L
h.1    6.964999
h.2    6.958602
h.3    6.952214
h.4    6.945835
h.5    6.939465
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AEE
h.1    0.892083
h.2    0.941978
h.3    0.984923
h.4    1.021887
h.5    1.053704
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AEP
h.1    1.041715
h.2    1.099056
h.3    1.146219
h.4    1.185011
h.5    1.216918
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ATO
h.1    0.847934
h.2    0.850489
h.3    0.853022
h.4    0.855532
h.5    0.858021
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
AWK
h.1    1.218118
h.2    1.283579
h.3    1.341230
h.4    1.392001
h.5    1.436714
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
CEG
h.1    6.923367
h.2    6.929419
h.3    6.935446
h.4    6.941449
h.5    6.947428
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
CNP
h.1    0.919040
h.2    0.942014
h.3    0.963540
h.4    0.983709
h.5    1.002608
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
D
h.1    1.551380
h.2    1.562180
h.3    1.572374
h.4    1.581998
h.5    1.591081
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
DTE
h.1    0.907894
h.2    0.920256
h.3    0.932116
h.4    0.943494
h.5    0.954411
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
DUK
h.1    0.830228
h.2    0.842759
h.3    0.854652
h.4    0.865938
h.5    0.876650
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ED
h.1    0.962360
h.2    0.975546
h.3    0.987971
h.4    0.999679
h.5    1.010713
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
EIX
h.1    1.561912
h.2    1.573120
h.3    1.584142
h.4    1.594982
h.5    1.605644
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ES
h.1    1.990270
h.2    1.990042
h.3    1.989825
h.4    1.989616
h.5    1.989417
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ETR
h.1    1.431909
h.2    1.515111
h.3    1.568734
h.4    1.603293
h.5    1.625565
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
EXC
h.1    0.918432
h.2    0.966841
h.3    1.010774
h.4    1.050647
h.5    1.086833
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
FE
h.1    0.720787
h.2    0.733136
h.3    0.745271
h.4    0.757196
h.5    0.768914
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NEE
h.1    1.835709
h.2    1.875024
h.3    1.912030
h.4    1.946864
h.5    1.979652
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NRG
h.1    5.340305
h.2    5.349094
h.3    5.357869
h.4    5.366630
h.5    5.375376
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
PCG
h.1    1.736179
h.2    1.740263
h.3    1.744309
h.4    1.748316
h.5    1.752285
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
PEG
h.1    1.090601
h.2    1.098373
h.3    1.105972
h.4    1.113400
h.5    1.120662
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
PPL
h.1    0.904859
h.2    0.928561
h.3    0.950331
h.4    0.970325
h.5    0.988688
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
SO
h.1    0.910383
h.2    0.943751
h.3    0.972768
h.4    0.998001
h.5    1.019944
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
SRE
h.1    1.407389
h.2    1.414378
h.3    1.421265
h.4    1.428050
h.5    1.434737
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
VST
h.1    6.938217
h.2    6.956289
h.3    6.974306
h.4    6.992267
h.5    7.010173
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
WEC
h.1    0.768377
h.2    0.776347
h.3    0.784170
h.4    0.791849
h.5    0.799388
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
XEL
h.1    1.153201
h.2    1.206826
h.3    1.249886
h.4    1.284463
h.5    1.312227
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
CRH
h.1    2.646394
h.2    2.667565
h.3    2.687901
h.4    2.707433
h.5    2.726195
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
CSX
h.1    1.141489
h.2    1.145669
h.3    1.149819
h.4    1.153941
h.5    1.158035
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
DE
h.1    1.755526
h.2    1.797107
h.3    1.836720
h.4    1.874458
h.5    1.910410
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
EME
h.1    2.789133
h.2    2.889508
h.3    2.980485
h.4    3.062943
h.5    3.137680
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
EMR
h.1    1.806919
h.2    1.912467
h.3    1.992459
h.4    2.053083
h.5    2.099027
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ETN
h.1    2.207573
h.2    2.327700
h.3    2.429653
h.4    2.516182
h.5    2.589620
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
FAST
h.1    1.833263
h.2    1.901978
h.3    1.933717
h.4    1.948377
h.5    1.955148
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
FTV
h.1    1.466667
h.2    1.520105
h.3    1.568374
h.4    1.611974
h.5    1.651355
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
HUBB
h.1    2.730706
h.2    2.737156
h.3    2.743335
h.4    2.749253
h.5    2.754922
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
HWM
h.1    2.606430
h.2    2.687562
h.3    2.758035
h.4    2.819249
h.5    2.872421
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
MLM
h.1    1.362012
h.2    1.377297
h.3    1.392303
h.4    1.407035
h.5    1.421499
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
MTZ
h.1    5.661829
h.2    5.696496
h.3    5.728735
h.4    5.758715
h.5    5.786594
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NSC
h.1    1.409201
h.2    1.428945
h.3    1.448144
h.4    1.466815
h.5    1.484971
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
PH
h.1    1.613785
h.2    1.728636
h.3    1.832211
h.4    1.925616
h.5    2.009850
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
PWR
h.1    3.608521
h.2    3.619705
h.3    3.630580
h.4    3.641154
h.5    3.651436
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ROK
h.1    2.993274
h.2    3.081692
h.3    3.151561
h.4    3.206772
h.5    3.250402
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
TRMB
h.1    2.745839
h.2    2.824894
h.3    2.897077
h.4    2.962986
h.5    3.023166
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
TT
h.1    2.056471
h.2    2.079505
h.3    2.101025
h.4    2.121131
h.5    2.139915
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
UNP
h.1    1.509057
h.2    1.557561
h.3    1.592819
h.4    1.618448
h.5    1.637079
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
URI
h.1    4.182604
h.2    4.584058
h.3    4.623922
h.4    4.627880
h.5    4.628273
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
VMC
h.1    1.427318
h.2    1.453410
h.3    1.478467
h.4    1.502531
h.5    1.525642
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
WWD
h.1    2.838835
h.2    2.915518
h.3    2.976181
h.4    3.024171
h.5    3.062135
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
6443.TW
h.1    20.369259
h.2    19.564401
h.3    18.808076
h.4    18.097357
h.5    17.429494
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
Skipping 66T.BE because it is empty.
Skipping AOR.BE because it is empty.
ARRY
h.1    20.649277
h.2    20.654062
h.3    20.658814
h.4    20.663531
h.5    20.668215
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
CSIQ
h.1    23.269419
h.2    23.102920
h.3    22.940705
h.4    22.782661
h.5    22.628683
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
CWEN
h.1    2.226040
h.2    2.267058
h.3    2.306046
h.4    2.343105
h.5    2.378330
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
DORL.TA
h.1    8.026032
h.2    7.993131
h.3    7.961570
h.4    7.931297
h.5    7.902258
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
DQ
h.1    12.976656
h.2    13.007033
h.3    13.037136
h.4    13.066969
h.5    13.096533
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ENLT
h.1    5.283803
h.2    5.283803
h.3    5.283803
h.4    5.283803
h.5    5.283803
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ENPH
h.1    13.547685
h.2    13.547593
h.3    13.547501
h.4    13.547411
h.5    13.547320
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
ENRG.TA
h.1    3.743094
h.2    3.742588
h.3    3.742084
h.4    3.741582
h.5    3.741081
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
FGSGF
h.1    6.820861
h.2    6.959579
h.3    6.962402
h.4    6.962459
h.5    6.962460
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
FSLR
h.1    8.704009
h.2    9.519127
h.3    9.779773
h.4    9.863118
h.5    9.889769
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
GCPEF
h.1    492.452595
h.2    558.106763
h.3    623.760930
h.4    689.415098
h.5    755.069265
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
GRE.MC
h.1    5.023774
h.2    5.116171
h.3    5.198929
h.4    5.273054
h.5    5.339446
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
HASI
h.1    4.840545
h.2    5.109183
h.3    5.358192
h.4    5.589006
h.5    5.802956
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
JKS
h.1     9.292500
h.2     9.612752
h.3     9.913647
h.4    10.196355
h.5    10.461975
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NOFR.TA
h.1    3.841717
h.2    3.840889
h.3    3.840066
h.4    3.839251
h.5    3.838442
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
NXT
h.1    12.261370
h.2    12.262020
h.3    12.262668
h.4    12.263313
h.5    12.263955
Name: 2025-12-30 00:00:00, dtype: float64
----------------------------------------
RUN
h.1    23.332229
h.2    23.440767
h.3    23.546921
h.4    23.650742
h.5    23.752282
Name: 2025-12-30 00:00:00, dtype: float64

In [68]:
print(garch_results)
#Tickers with Statistically Significant Volatility Models (95% Confidence):
#                          [["OGE", "SU", "NI", "JCI", "IDA", "ET", "APH", "AEIS",
#                            "SBAC", "GDS", "EQIX", "CCI", "AMT", "AJBU.SI",
#                            "3006.TW", "2344.TW", "1686.HK", "0788.HK", "SHLS",
#                            "NOFR.TA", "JKS", "ENRG.TA", "ENLT", "DQ",
#                            "CWEN", "CSIQ", "ARRY", "66T.BE", "6443.TW", "VMC",
#                            "PH", "MLM", "HWM", "FTV", "ETN", "CRH",
#                            "XEL", "VST", "SRE", "SO", "PPL", "NRG", "FE", "EXC",
#                            "ETR", "EIX", "ED", "DUK", "DTE", "D", "CNP", "CEG",
#                            "AWK", "ATO", "VALT.L", "TECK", "STLD", "PKX.BE",
#                            "IZ1.BE", "HWHG.BE", "FVJA.BE", "FCX", "TER", "RMBS",
#                            "QCOM", "ON", "NXPI", "NVMI", "NVDA", "MU", "MPWR",
#                            "MCHP", "LRCX", "KLAC", "AVGO", "ASML", "ADI"]]

{'ADI':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                    ADI   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2518.46
Distribution:                  Normal   AIC:                           5044.92
Method:            Maximum Likelihood   BIC:                           5065.42
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                                 Mean Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
mu             0.0423  4.867e-02      0.868      0.385 [-5.313e-02,  0.138]
                              Volatility Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
omega          0.2227      0.183      1.216      0.224    [ -0.136,  0.582]
alpha[1]       0.0565  3.326e-02      1.700  8.922e-02 [-8.663e-03,  0.122]
beta[1]        0.8819  7.430e-02     11.869  1.707e-32    [  0.736,  1.028]
===========================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb5b2f00, 'ALAB':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   ALAB   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -1683.09
Distribution:                  Normal   AIC:                           3374.19
Method:            Maximum Likelihood   BIC:                           3391.44
                                        No. Observations:                  551
Date:                Thu, Apr 16 2026   Df Residuals:                      550
Time:                        10:49:41   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.3035      0.219      1.384      0.167 [ -0.126,  0.733]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          2.3371      1.261      1.853  6.382e-02      [ -0.134,  4.808]
alpha[1]       0.0000  3.377e-03      0.000      1.000 [-6.619e-03,6.619e-03]
beta[1]        0.9097  4.263e-02     21.338 5.011e-101      [  0.826,  0.993]
=============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb5b32f0, 'AMAT':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   AMAT   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2865.77
Distribution:                  Normal   AIC:                           5739.54
Method:            Maximum Likelihood   BIC:                           5760.03
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                                 Mean Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
mu             0.0871  7.023e-02      1.240      0.215 [-5.055e-02,  0.225]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          0.1864      0.391      0.477      0.634      [ -0.580,  0.953]
alpha[1]       0.0223  2.956e-02      0.754      0.451 [-3.566e-02,8.023e-02]
beta[1]        0.9464  9.060e-02     10.445  1.545e-25      [  0.769,  1.124]
=============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb5b0620, 'AMD':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                    AMD   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -3147.86
Distribution:                  Normal   AIC:                           6303.72
Method:            Maximum Likelihood   BIC:                           6324.21
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                                 Mean Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
mu             0.0878  9.101e-02      0.965      0.334 [-9.053e-02,  0.266]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          1.5877      0.855      1.858  6.318e-02   [-8.717e-02,  3.263]
alpha[1]       0.0394  2.614e-02      1.507      0.132 [-1.183e-02,9.065e-02]
beta[1]        0.7936  8.611e-02      9.216  3.075e-20      [  0.625,  0.962]
=============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x793925649c40, 'ASML':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   ASML   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2828.40
Distribution:                  Normal   AIC:                           5664.80
Method:            Maximum Likelihood   BIC:                           5685.29
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                                 Mean Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
mu             0.0796  6.766e-02      1.176      0.239 [-5.302e-02,  0.212]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          0.0690  7.749e-02      0.890      0.373   [-8.290e-02,  0.221]
alpha[1]       0.0190  1.047e-02      1.811  7.020e-02 [-1.564e-03,3.950e-02]
beta[1]        0.9690  2.161e-02     44.843      0.000      [  0.927,  1.011]
=============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb5b0d40, 'AVGO':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   AVGO   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2874.94
Distribution:                  Normal   AIC:                           5757.88
Method:            Maximum Likelihood   BIC:                           5778.37
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                                 Mean Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
mu             0.1198  6.935e-02      1.727  8.417e-02 [-1.616e-02,  0.256]
                             Volatility Model
==========================================================================
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
omega          1.2959      0.407      3.185  1.448e-03   [  0.498,  2.093]
alpha[1]       0.1372  6.655e-02      2.062  3.921e-02 [6.785e-03,  0.268]
beta[1]        0.6739  6.939e-02      9.712  2.692e-22   [  0.538,  0.810]
==========================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb527a70, 'CRDO':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   CRDO   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -3557.85
Distribution:                  Normal   AIC:                           7123.71
Method:            Maximum Likelihood   BIC:                           7144.12
                                        No. Observations:                 1217
Date:                Thu, Apr 16 2026   Df Residuals:                     1216
Time:                        10:49:41   Df Model:                            1
                                Mean Model
==========================================================================
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
mu             0.3047      0.130      2.341  1.921e-02 [4.963e-02,  0.560]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          0.2693      0.120      2.245  2.477e-02    [3.419e-02,  0.504]
alpha[1]   2.6884e-03  4.179e-03      0.643      0.520 [-5.502e-03,1.088e-02]
beta[1]        0.9843  6.410e-03    153.552      0.000      [  0.972,  0.997]
=============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb5b1970, 'ENTG':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   ENTG   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -3083.34
Distribution:                  Normal   AIC:                           6174.69
Method:            Maximum Likelihood   BIC:                           6195.18
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu             0.0199  7.986e-02      0.249      0.803 [ -0.137,  0.176]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          0.3155      0.376      0.840      0.401      [ -0.421,  1.052]
alpha[1]       0.0297  2.066e-02      1.438      0.150 [-1.078e-02,7.021e-02]
beta[1]        0.9347  5.800e-02     16.114  2.028e-58      [  0.821,  1.048]
=============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x79391fe00560, 'INTC':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   INTC   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2999.11
Distribution:                  Normal   AIC:                           6006.22
Method:            Maximum Likelihood   BIC:                           6026.71
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                               Mean Model
========================================================================
                 coef    std err          t      P>|t|  95.0% Conf. Int.
------------------------------------------------------------------------
mu            -0.0135  7.613e-02     -0.177      0.860 [ -0.163,  0.136]
                              Volatility Model
===========================================================================
                 coef    std err          t      P>|t|     95.0% Conf. Int.
---------------------------------------------------------------------------
omega          2.5233      1.550      1.628      0.104    [ -0.515,  5.562]
alpha[1]       0.1924      0.169      1.139      0.255    [ -0.139,  0.524]
beta[1]        0.5119      0.283      1.812  7.001e-02 [-4.185e-02,  1.066]
===========================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb5b0980, 'KLAC':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   KLAC   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2829.91
Distribution:                  Normal   AIC:                           5667.82
Method:            Maximum Likelihood   BIC:                           5688.31
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                                Mean Model
==========================================================================
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
mu             0.1328  6.642e-02      2.000  4.554e-02 [2.637e-03,  0.263]
                               Volatility Model
=============================================================================
                 coef    std err          t      P>|t|       95.0% Conf. Int.
-----------------------------------------------------------------------------
omega          0.1321      0.103      1.282      0.200   [-6.979e-02,  0.334]
alpha[1]       0.0269  1.596e-02      1.684  9.216e-02 [-4.402e-03,5.815e-02]
beta[1]        0.9498  2.999e-02     31.667 4.416e-220      [  0.891,  1.009]
=============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x7938eb5b2330, 'LRCX':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   LRCX   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2919.35
Distribution:                  Normal   AIC:                           5846.71
Method:            Maximum Likelihood   BIC:                           5867.20
                                        No. Observations:                 1240
Date:                Thu, Apr 16 2026   Df Residuals:                     1239
Time:                        10:49:41   Df Model:                            1
                                Mean Model
==========================================================================
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
mu             0.1427  7.135e-02      2.000  4.550e-02 [2.860e-03,  0.283]
                              Volatility Model
============================================================================
                 coef    std err          t      P>|t|      95.0% Conf. Int.
----------------------------------------------------------------------------
omega          0.1631      0.104      1.571      0.116  [-4.042e-02,  0.367]
alpha[1]       0.0328  1.372e-02      2.389  1.689e-02 [5.889e-03,5.967e-02]
beta[1]        0.9428  2.415e-02     39.043      0.000     [  0.895,  0.990]
============================================================================

Covariance estimator: robust
ARCHModelResult, id: 0x79391fe02e40, 'MCHP':                      Constant Mean - GARCH Model Results
==============================================================================
Dep. Variable:                   MCHP   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -2839.27
Distribution:                  Normal   AIC:                           5686.53

In [69]:
filtered_vol = combined_vol[["OGE", "SU", "NI", "JCI", "IDA", "ET", "APH", "AEIS",
                            "SBAC", "GDS", "EQIX", "CCI", "AMT", "AJBU.SI",
                            "3006.TW", "2344.TW", "1686.HK", "0788.HK", "SHLS",
                            "NOFR.TA", "JKS", "ENRG.TA", "ENLT", "DQ",
                            "CWEN", "CSIQ", "ARRY", "66T.BE", "6443.TW", "VMC",
                            "PH", "MLM", "HWM", "FTV", "ETN", "CRH",
                            "XEL", "VST", "SRE", "SO", "PPL", "NRG", "FE", "EXC",
                            "ETR", "EIX", "ED", "DUK", "DTE", "D", "CNP", "CEG",
                            "AWK", "ATO", "VALT.L", "TECK", "STLD", "PKX.BE",
                            "IZ1.BE", "HWHG.BE", "FVJA.BE", "FCX", "TER", "RMBS",
                            "QCOM", "ON", "NXPI", "NVMI", "NVDA", "MU", "MPWR",
                            "MCHP", "LRCX", "KLAC", "AVGO", "ASML", "ADI"]]

In [70]:
trad_week_vols = {}

for col, res in garch_results.items():
    forecast = res.forecast(horizon=5)
    trading_week_vol = np.sqrt(forecast.variance.iloc[-1].sum())
    trad_week_vols[col] = trading_week_vol

trad_week_vol_data = (pd.Series(trad_week_vols, name="trad_week_vol").sort_values(ascending=False))

In [71]:
filtered_week_vol_data = trad_week_vol_data[["OGE", "SU", "NI", "JCI", "IDA", "ET", "APH", "AEIS",
                            "SBAC", "GDS", "EQIX", "CCI", "AMT", "AJBU.SI",
                            "3006.TW", "2344.TW", "1686.HK", "0788.HK", "SHLS",
                            "NOFR.TA", "JKS", "ENRG.TA", "ENLT", "DQ",
                            "CWEN", "CSIQ", "ARRY", "6443.TW", "VMC",
                            "PH", "MLM", "HWM", "FTV", "ETN", "CRH",
                            "XEL", "VST", "SRE", "SO", "PPL", "NRG", "FE", "EXC",
                            "ETR", "EIX", "ED", "DUK", "DTE", "D", "CNP", "CEG",
                            "AWK", "ATO", "VALT.L", "TECK", "STLD",
                            "FCX", "TER", "RMBS",
                            "QCOM", "ON", "NXPI", "NVMI", "NVDA", "MU", "MPWR",
                            "MCHP", "LRCX", "KLAC", "AVGO", "ASML", "ADI"]]         #KeyError: "['66T.BE', 'PKX.BE', 'IZ1.BE', 'HWHG.BE', 'FVJA.BE'] not in index"
                                                                                    #Removed as 0 data included

In [72]:
filtered_week_vol_data = filtered_week_vol_data.sort_values(ascending=True).to_frame(name="trad_week_vol")

In [73]:
ticker_industry = {}

for ticker in filtered_week_vol_data.index:
        info = yf.Ticker(ticker).info
        ticker_industry[ticker] = info.get("industry", None)

ticker_industry_data = pd.Series(ticker_industry, name="industry")
filtered_week_vol_data = filtered_week_vol_data.join(ticker_industry_data)

In [74]:
filtered_week_vol_data

         trad_week_vol                                 industry
FE            1.930105           Utilities - Regulated Electric
ET            2.064743                      Oil & Gas Midstream
ATO           2.065187                Utilities - Regulated Gas
DUK           2.066453           Utilities - Regulated Electric
IDA           2.077802           Utilities - Regulated Electric
OGE           2.135198           Utilities - Regulated Electric
DTE           2.158280           Utilities - Regulated Electric
AJBU.SI       2.158724                            REIT - Office
PPL           2.177789           Utilities - Regulated Electric
NI            2.178205                Utilities - Regulated Gas
CNP           2.193379           Utilities - Regulated Electric
SO            2.201101           Utilities - Regulated Electric
ED            2.221772           Utilities - Regulated Electric
EXC           2.243552           Utilities - Regulated Electric
XEL           2.491305           Utilities - Regulated Electric
AWK           2.582952              Utilities - Regulated Water
MLM           2.638209                       Building Materials
SRE           2.665674                  Utilities - Diversified
VMC           2.717971                       Building Materials
ETR           2.782914           Utilities - Regulated Electric
FTV           2.796154       Scientific & Technical Instruments
D             2.803393           Utilities - Regulated Electric
EIX           2.814214           Utilities - Regulated Electric
CCI           2.908647                         REIT - Specialty
SU            2.914291                     Oil & Gas Integrated
AMT           2.988477                         REIT - Specialty
0788.HK       3.007376                         Telecom Services
PH            3.018294           Specialty Industrial Machinery
EQIX          3.048706                         REIT - Specialty
SBAC          3.147769                         REIT - Specialty
CWEN          3.394198                    Utilities - Renewable
JCI           3.395335            Building Products & Equipment
ADI           3.470213                           Semiconductors
ETN           3.474296           Specialty Industrial Machinery
CRH           3.665445                       Building Materials
HWM           3.707249                      Aerospace & Defense
1686.HK       3.833707                     Real Estate Services
QCOM          3.875174                           Semiconductors
NXPI          4.020518                           Semiconductors
APH           4.039040                    Electronic Components
STLD          4.062347                                    Steel
ENRG.TA       4.325555                    Utilities - Renewable
NOFR.TA       4.381822                                    Solar
MCHP          4.712150                           Semiconductors
ASML          4.716534      Semiconductor Equipment & Materials
AEIS          4.777637             Electrical Equipment & Parts
KLAC          4.796311      Semiconductor Equipment & Materials
FCX           4.882781                                   Copper
TECK          4.980561         Other Industrial Metals & Mining
AVGO          5.042059                           Semiconductors
ENLT          5.139943                    Utilities - Renewable
NRG           5.175836  Utilities - Independent Power Producers
LRCX          5.591434      Semiconductor Equipment & Materials
NVDA          5.602043                           Semiconductors
MPWR          5.677108                           Semiconductors
NVMI          5.826919      Semiconductor Equipment & Materials
ON            5.840000                           Semiconductors
CEG           5.888727  Utilities - Independent Power Producers
VALT.L        5.895856           Other Precious Metals & Mining
VST           5.905189  Utilities - Independent Power Producers
RMBS          6.289618                           Semiconductors
TER           6.833393      Semiconductor Equipment & Materials
JKS           7.034005                                    Solar
GDS           7.132473          Information Technology Services
MU            7.703406                           Semiconductors
DQ            8.073681      Semiconductor Equipment & Materials
2344.TW       8.456165                           Semiconductors
SHLS          9.570440                                    Solar
6443.TW       9.709201                                    Solar
ARRY         10.163361                                    Solar
3006.TW      10.575986                           Semiconductors
CSIQ         10.710947                                    Solar